package main

import (
	"deliportal-api/config"
	"deliportal-api/controller"
	"deliportal-api/middleware"
	"deliportal-api/repository"
	"deliportal-api/service"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

var (
	db                                        *gorm.DB                                             = config.ConnectDataBase()
	divisionRepository                        repository.DivisionRepository                        = repository.NewDivisionRepository(db)
	departmentRepository                      repository.DepartmentRepository                      = repository.NewDepartmentRepository(db)
	sectionRepository                         repository.SectionRepository                         = repository.NewSectionRepository(db)
	positionRepository                        repository.PositionRepository                        = repository.NewPositionRepository(db)
	locationRepository                        repository.LocationRepository                        = repository.NewLocationRepository(db)
	employeeRepository                        repository.EmployeeRepository                        = repository.NewEmployeeRepository(db)
	userRepository                            repository.UserRepository                            = repository.NewUserRepository(db)
	formRepository                            repository.FormRepository                            = repository.NewFormRepository(db)
	formTypeRepository                        repository.FormTypeRepository                        = repository.NewFormTypeRepository(db)
	roleRepository                            repository.RoleRepository                            = repository.NewRoleRepository(db)
	userRoleRepository                        repository.UserRoleRepository                        = repository.NewUserRoleRepository(db)
	roleFormRepository                        repository.RoleFormRepository                        = repository.NewRoleFormRepository(db)
	businessUnitRepository                    repository.BusinessUnitRepository                    = repository.NewBusinessUnitRepository(db)
	companyManagementTypeRepository           repository.CompanyManagementTypeRepository           = repository.NewCompanyManagementTypeRepository(db)
	licenseTypeRepository                     repository.LicenseTypeRepository                     = repository.NewLicenseTypeRepository(db)
	emailQueueTypeRepository                  repository.EmailQueueTypeRepository                  = repository.NewEmailQueueTypeRepository(db)
	emailQueueRepository                      repository.EmailQueueRepository                      = repository.NewEmailQueueRepository(db)
	emailQueueReferenceRepository             repository.EmailQueueReferenceRepository             = repository.NewEmailQueueReferenceRepository(db)
	companyRepository                         repository.CompanyRepository                         = repository.NewCompanyRepository(db)
	companyShareholderRepository              repository.CompanyShareholderRepository              = repository.NewCompanyShareholderRepository(db)
	companyManagementRepository               repository.CompanyManagementRepository               = repository.NewCompanyManagementRepository(db)
	companyLicenseRepository                  repository.CompanyLicenseRepository                  = repository.NewCompanyLicenseRepository(db)
	companyLicenseRenewalTracingRepository    repository.CompanyLicenseRenewalTracingRepository    = repository.NewCompanyLicenseRenewalTracingRepository(db)
	userCompanyRestrictionRepository          repository.UserCompanyRestrictionRepository          = repository.NewUserCompanyRestrictionRepository(db)
	companyGroupRepository                    repository.CompanyGroupRepository                    = repository.NewCompanyGroupRepository(db)
	companyGroupCompanyRepository             repository.CompanyGroupCompanyRepository             = repository.NewCompanyGroupCompanyRepository(db)
	groupLicenseTypeRepository                repository.GroupLicenseTypeRepository                = repository.NewGroupLicenseTypeRepository(db)
	internalMemoTypeRepository                repository.InternalMemoTypeRepository                = repository.NewInternalMemoTypeRepository(db)
	internalMemoRepository                    repository.InternalMemoRepository                    = repository.NewInternalMemoRepository(db)
	internalMemoCirculationRepository         repository.InternalMemoCirculationRepository         = repository.NewInternalMemoCirculationRepository(db)
	internalMemoAttachmentRepository          repository.InternalMemoAttachmentRepository          = repository.NewInternalMemoAttachmentRepository(db)
	internalMemoTracingRepository             repository.InternalMemoTracingRepository             = repository.NewInternalMemoTracingRepository(db)
	imDefaultCirculationRepository            repository.ImDefaultCirculationRepository            = repository.NewImDefaultCirculationRepository(db)
	vehicleCategoryRepository                 repository.VehicleCategoryRepository                 = repository.NewVehicleCategoryRepository(db)
	vehicleMerkRepository                     repository.VehicleMerkRepository                     = repository.NewVehicleMerkRepository(db)
	vehicleTypeRepository                     repository.VehicleTypeRepository                     = repository.NewVehicleTypeRepository(db)
	vehicleRepository                         repository.VehicleRepository                         = repository.NewVehicleRepository(db)
	vehicleLicenseTypeRepository              repository.VehicleLicenseTypeRepository              = repository.NewVehicleLicenseTypeRepository(db)
	companyAkteRepository                     repository.CompanyAkteRepository                     = repository.NewCompanyAkteRepository(db)
	companyShareholderHistoryRepository       repository.CompanyShareholderHistoryRepository       = repository.NewCompanyShareholderHistoryRepository(db)
	companyShareholderHistoryDetailRepository repository.CompanyShareholderHistoryDetailRepository = repository.NewCompanyShareholderHistoryDetailRepository(db)
	companyManagementHistoryRepository        repository.CompanyManagementHistoryRepository        = repository.NewCompanyManagementHistoryRepository(db)
	companyManagementHistoryDetailRepository  repository.CompanyManagementHistoryDetailRepository  = repository.NewCompanyManagementHistoryDetailRepository(db)
	leavetypesRepository                      repository.LeaveTypesRepository                      = repository.NewLeaveTypeRepository(db)
	nonworkingtypeRepository                  repository.NonWorkingTypeRepository                  = repository.NewNonWorkingTypeRepository(db)
	nonworkingdayRepository                   repository.NonWorkingDayRepository                   = repository.NewNonWorkingDayRepository(db)
	employeeleavecreditRepository             repository.EmployeeLeaveCreditRepository             = repository.NewEmployeeLeaveCreditRepository(db)
	employeeleaverequestRepository            repository.EmployeeLeaveRequestRepository            = repository.NewEmployeeLeaveRequestRepository(db)
	employeeleaverequestapprovalRepository    repository.EmployeeLeaveRequestApprovalRepository    = repository.NewEmployeeLeaveRequestApprovalRepository(db)
	employeeleaverequesttracingRepository     repository.EmployeeLeaveRequestTracingRepository     = repository.NewEmployeeLeaveRequestTracingRepository(db)
	employeeLeaveRequestDumpRepository        repository.EmployeeLeaveRequestDumpRepository        = repository.NewEmployeeLeaveRequestDumpRepository(db)
	authService                               service.AuthService                                  = service.NewAuthService(userRepository)
	divisionService                           service.DivisionService                              = service.NewDivisionService(divisionRepository)
	departmentService                         service.DepartmentService                            = service.NewDepartmentService(departmentRepository)
	sectionService                            service.SectionService                               = service.NewSectionService(sectionRepository)
	positionService                           service.PositionService                              = service.NewPositionService(positionRepository)
	locationService                           service.LocationService                              = service.NewLocationService(locationRepository)
	employeeService                           service.EmployeeService                              = service.NewEmployeeService(employeeRepository)
	userService                               service.UserService                                  = service.NewUserService(userRepository)
	formService                               service.FormService                                  = service.NewFormService(formRepository)
	formTypeService                           service.FormTypeService                              = service.NewFormTypeService(formTypeRepository)
	roleService                               service.RoleService                                  = service.NewRoleService(roleRepository)
	userRoleService                           service.UserRoleService                              = service.NewUserRoleService(userRoleRepository)
	roleFormService                           service.RoleFormService                              = service.NewRoleFormService(roleFormRepository)
	businessUnitService                       service.BusinessUnitService                          = service.NewBusinessUnitService(businessUnitRepository)
	companyManagementTypeService              service.CompanyManagementTypeService                 = service.NewCompanyManagementTypeService(companyManagementTypeRepository)
	licenseTypeService                        service.LicenseTypeService                           = service.NewLicenseTypeService(licenseTypeRepository)
	companyLicenseRenewalTracingService       service.CompanyLicenseRenewalTracingService          = service.NewCompanyLicenseRenewalTracingService(companyLicenseRenewalTracingRepository)
	emailQueueTypeService                     service.EmailQueueTypeService                        = service.NewEmailQueueTypeService(emailQueueTypeRepository)
	emailQueueService                         service.EmailQueueService                            = service.NewEmailQueueService(emailQueueRepository)
	emailQueueReferenceService                service.EmailQueueReferenceService                   = service.NewEmailQueueReferenceService(emailQueueReferenceRepository)
	companyService                            service.CompanyService                               = service.NewCompanyService(companyRepository)
	companyShareholderService                 service.CompanyShareholderService                    = service.NewCompanyShareholderService(companyShareholderRepository)
	companyManagementService                  service.CompanyManagementService                     = service.NewCompanyManagementService(companyManagementRepository)
	companyLicenseService                     service.CompanyLicenseService                        = service.NewCompanyLicenseService(companyLicenseRepository)
	userCompanyRestrictionService             service.UserCompanyRestrictionService                = service.NewUserCompanyRestrictionService(userCompanyRestrictionRepository)
	companyGroupService                       service.CompanyGroupService                          = service.NewCompanyGroupService(companyGroupRepository)
	companyGroupCompanyService                service.CompanyGroupCompanyService                   = service.NewCompanyGroupCompanyService(companyGroupCompanyRepository)
	groupLicenseTypeService                   service.GroupLicenseTypeService                      = service.NewGroupLicenseTypeService(groupLicenseTypeRepository)
	internalMemoTypeService                   service.InternalMemoTypeService                      = service.NewInternalMemoTypeService(internalMemoTypeRepository)
	internalMemoService                       service.InternalMemoService                          = service.NewInternalMemoService(internalMemoRepository)
	internalMemoCirculationService            service.InternalMemoCirculationService               = service.NewInternalMemoCirculationService(internalMemoCirculationRepository)
	internalMemoAttachmentService             service.InternalMemoAttachmentService                = service.NewInternalMemoAttachmentService(internalMemoAttachmentRepository)
	internalMemoTracingService                service.InternalMemoTracingService                   = service.NewInternalMemoTracingService(internalMemoTracingRepository)
	imDefaultCirculationService               service.ImDefaultCirculationService                  = service.NewImDefaultCirculationService(imDefaultCirculationRepository)
	vehicleCategoryService                    service.VehicleCategoryService                       = service.NewVehicleCategoryService(vehicleCategoryRepository)
	vehicleMerkService                        service.VehicleMerkService                           = service.NewVehicleMerkService(vehicleMerkRepository)
	vehicleTypeService                        service.VehicleTypeService                           = service.NewVehicleTypeService(vehicleTypeRepository)
	vehicleService                            service.VehicleService                               = service.NewVehicleService(vehicleRepository)
	vehicleLicenseTypeService                 service.VehicleLicenseTypeService                    = service.NewVehicleLicenseTypeService(vehicleLicenseTypeRepository)
	companyAkteService                        service.CompanyAkteService                           = service.NewCompanyAkteService(companyAkteRepository)
	companyShareholderHistoryService          service.CompanyShareholderHistoryService             = service.NewCompanyShareholderHistoryService(companyShareholderHistoryRepository)
	companyShareholderHistoryDetailService    service.CompanyShareholderHistoryDetailService       = service.NewCompanyShareholderHistoryDetailService(companyShareholderHistoryDetailRepository)
	companyManagementHistoryService           service.CompanyManagementHistoryService              = service.NewCompanyManagementHistoryService(companyManagementHistoryRepository)
	companyManagementHistoryDetailService     service.CompanyManagementHistoryDetailService        = service.NewCompanyManagementHistoryDetailService(companyManagementHistoryDetailRepository)
	leavetypesService                         service.LeaveTypesService                            = service.NewLeaveTypesService(leavetypesRepository)
	nonworkingtypeService                     service.NonWorkingTypeService                        = service.NewNonWorkingTypeService(nonworkingtypeRepository)
	nonworkingdayService                      service.NonWorkingDayService                         = service.NewNonWorkingDayService(nonworkingdayRepository)
	employeeleavecreditService                service.EmployeeLeaveCreditService                   = service.NewEmployeeLeaveCreditService(employeeleavecreditRepository)
	employeeleaverequestService               service.EmployeeLeaveRequestService                  = service.NewEmployeeLeaveRequestService(employeeleaverequestRepository)
	employeeleaverequestapprovalService       service.EmployeeLeaveRequestApprovalService          = service.NewEmployeeLeaveRequestApprovalService(employeeleaverequestapprovalRepository)
	employeeleaverequesttracingService        service.EmployeeLeaveRequestTracingService           = service.NewEmployeeLeaveRequestTracingService(employeeleaverequesttracingRepository)
	employeeLeaveRequestDumpService           service.EmployeeLeaveRequestDumpService              = service.NewEmployeeLeaveRequestDumpService(employeeLeaveRequestDumpRepository)
	jwtService                                service.JWTService                                   = service.NewJWTService()
	authController                            controller.AuthController                            = controller.NewAuthController(authService, jwtService)
	divisionController                        controller.DivisionController                        = controller.NewDivisionController(divisionService, jwtService)
	departmentController                      controller.DepartmentController                      = controller.NewDepartmentController(departmentService, jwtService)
	sectionController                         controller.SectionController                         = controller.NewSectionController(sectionService, jwtService)
	positionController                        controller.PositionController                        = controller.NewPositionController(positionService, jwtService)
	locationController                        controller.LocationController                        = controller.NewLocationController(locationService, jwtService)
	employeeController                        controller.EmployeeController                        = controller.NewEmployeeController(employeeService, jwtService)
	userController                            controller.UserController                            = controller.NewUserController(userService, jwtService)
	formController                            controller.FormController                            = controller.NewFormController(formService, jwtService)
	formTypeController                        controller.FormTypeController                        = controller.NewFormTypeController(formTypeService, jwtService)
	roleController                            controller.RoleController                            = controller.NewRoleController(roleService, jwtService)
	userRoleController                        controller.UserRoleController                        = controller.NewUserRoleController(userRoleService, jwtService)
	roleFormController                        controller.RoleFormController                        = controller.NewRoleFormController(roleFormService, jwtService)
	businessUnitController                    controller.BusinessUnitController                    = controller.NewBusinessUnitController(businessUnitService, jwtService)
	companyManagementTypeController           controller.CompanyManagementTypeController           = controller.NewCompanyManagementTypeController(companyManagementTypeService, jwtService)
	licenseTypeController                     controller.LicenseTypeController                     = controller.NewLicenseTypeController(licenseTypeService, jwtService)
	emailQueueTypeController                  controller.EmailQueueTypeController                  = controller.NewEmailQueueTypeController(emailQueueTypeService, jwtService)
	emailQueueController                      controller.EmailQueueController                      = controller.NewEmailQueueController(emailQueueService, jwtService)
	emailQueueReferenceController             controller.EmailQueueReferenceController             = controller.NewEmailQueueReferenceController(emailQueueReferenceService, jwtService)
	companyController                         controller.CompanyController                         = controller.NewCompanyController(companyService, jwtService)
	companyShareholderController              controller.CompanyShareholderController              = controller.NewCompanyShareholderController(companyShareholderService, jwtService)
	companyManagementController               controller.CompanyManagementController               = controller.NewCompanyManagementController(companyManagementService, jwtService)
	companyLicenseController                  controller.CompanyLicenseController                  = controller.NewCompanyLicenseController(companyLicenseService, jwtService)
	companyLicenseRenewalTracingController    controller.CompanyLicenseRenewalTracingController    = controller.NewCompanyLicenseRenewalTracingController(companyLicenseRenewalTracingService, jwtService)
	userCompanyRestrictionController          controller.UserCompanyRestrictionController          = controller.NewUserCompanyRestrictionController(userCompanyRestrictionService, jwtService)
	companyGroupController                    controller.CompanyGroupController                    = controller.NewCompanyGroupController(companyGroupService, jwtService)
	companyGroupCompanyController             controller.CompanyGroupCompanyController             = controller.NewCompanyGroupCompanyController(companyGroupCompanyService, jwtService)
	groupLicenseTypeController                controller.GroupLicenseTypeController                = controller.NewGroupLicenseTypeController(groupLicenseTypeService, jwtService)
	internalMemoTypeController                controller.InternalMemoTypeController                = controller.NewInternalMemoTypeController(internalMemoTypeService, jwtService)
	internalMemoController                    controller.InternalMemoController                    = controller.NewInternalMemoController(internalMemoService, jwtService)
	internalMemoCirculationController         controller.InternalMemoCirculationController         = controller.NewInternalMemoCirculationController(internalMemoCirculationService, jwtService)
	internalMemoAttachmentController          controller.InternalMemoAttachmentController          = controller.NewInternalMemoAttachmentController(internalMemoAttachmentService, jwtService)
	internalMemoTracingController             controller.InternalMemoTracingController             = controller.NewInternalMemoTracingController(internalMemoTracingService, jwtService)
	imDefaultCirculationController            controller.ImDefaultCirculationController            = controller.NewImDefaultCirculationController(imDefaultCirculationService, jwtService)
	vehicleCategoryController                 controller.VehicleCategoryController                 = controller.NewVehicleCategoryController(vehicleCategoryService, jwtService)
	vehicleMerkController                     controller.VehicleMerkController                     = controller.NewVehicleMerkController(vehicleMerkService, jwtService)
	vehicleTypeController                     controller.VehicleTypeController                     = controller.NewVehicleTypeController(vehicleTypeService, jwtService)
	vehicleController                         controller.VehicleController                         = controller.NewVehicleController(vehicleService, jwtService)
	vehicleLicenseTypeController              controller.VehicleLicenseTypeController              = controller.NewVehicleLicenseTypeController(vehicleLicenseTypeService, jwtService)
	companyAkteController                     controller.CompanyAkteController                     = controller.NewCompanyAkteController(companyAkteService, jwtService)
	companyShareholderHistoryController       controller.CompanyShareholderHistoryController       = controller.NewCompanyShareholderHistoryController(companyShareholderHistoryService, jwtService)
	companyShareholderHistoryDetailController controller.CompanyShareholderHistoryDetailController = controller.NewCompanyShareholderHistoryDetailController(companyShareholderHistoryDetailService, jwtService)
	companyManagementHistoryController        controller.CompanyManagementHistoryController        = controller.NewCompanyManagementHistoryController(companyManagementHistoryService, jwtService)
	companyManagementHistoryDetailController  controller.CompanyManagementHistoryDetailController  = controller.NewCompanyManagementHistoryDetailController(companyManagementHistoryDetailService, jwtService)
	leavetypesController                      controller.LeaveTypesController                      = controller.NewLeaveTypesController(leavetypesService, jwtService)
	nonworkingtypeController                  controller.NonWorkingTypeController                  = controller.NewNonWorkingTypeController(nonworkingtypeService, jwtService)
	nonworkingdayController                   controller.NonWorkingDayController                   = controller.NewNonWorkingDayController(nonworkingdayService, jwtService)
	employeeleavecreditController             controller.EmployeeLeaveCreditController             = controller.NewEmployeeLeaveCreditController(employeeleavecreditService, jwtService)
	employeeleaverequestController            controller.EmployeeLeaveRequestController            = controller.NewEmployeeLeaveRequestController(employeeleaverequestService, jwtService)
	employeeleaverequestapprovalController    controller.EmployeeLeaveRequestApprovalController    = controller.NewEmployeeLeaveRequestApprovalController(employeeleaverequestapprovalService, jwtService)
	employeeleaverequesttracingController     controller.EmployeeLeaveRequestTracingController     = controller.NewEmployeeLeaveRequestTracingController(employeeleaverequesttracingService, jwtService)
	employeeLeaveRequestDumpController        controller.EmployeeLeaveRequestDumpController        = controller.NewEmployeeLeaveRequestDumpController(employeeLeaveRequestDumpService, jwtService)
)

func main() {
	defer config.CloseDatabaseConnection(db)

	r := gin.Default()

	authGroup := r.Group("/api/auth")
	{
		authGroup.POST("/login", authController.Login)
		authGroup.POST("/register", authController.Register)
		authGroup.POST("/checkEx", authController.CheckExisting)
		authGroup.POST("/sendMail", authController.SendMail)
		authGroup.POST("/sendMail2", authController.SendMail2)
		authGroup.POST("/password/:username/:email", authController.UpdateDataPassword)
		authGroup.POST("/upReq/:username/:email", authController.UpdateDataRequest)
		authGroup.POST("/uploadDocument", authController.UploadDocument)
	}

	divisionGroup := r.Group("/api/division", middleware.AuthorizeJWT(jwtService))
	{
		divisionGroup.GET("/", divisionController.CountDivisionAll)
		divisionGroup.GET("/all", divisionController.FindDivisions)
		divisionGroup.GET("/list/:limit/:offset/:order/:dir", divisionController.FindDivisionsOffset)
		divisionGroup.GET("/search/:limit/:offset/:order/:dir/:search", divisionController.SearchDivision)
		divisionGroup.GET("/countSearch/:search", divisionController.CountSearchDivision)
		divisionGroup.GET("/:id", divisionController.FindDivisionById)
		divisionGroup.GET("/CountDivisionName/:search", divisionController.CountDivisionName)
		divisionGroup.GET("/exc/:id", divisionController.FindExcDivision)
		divisionGroup.POST("/", divisionController.InsertDivision)
		divisionGroup.PUT("/:id", divisionController.UpdateDivision)
		divisionGroup.DELETE("/:id", divisionController.DeleteDivision)
	}

	departmentGroup := r.Group("/api/department", middleware.AuthorizeJWT(jwtService))
	{
		departmentGroup.GET("/", departmentController.CountDepartmentAll)
		departmentGroup.GET("/all", departmentController.FindDepartments)
		departmentGroup.GET("/list/:limit/:offset/:order/:dir", departmentController.FindDepartmentsOffset)
		departmentGroup.GET("/search/:limit/:offset/:order/:dir/:search", departmentController.SearchDepartment)
		departmentGroup.GET("/countSearch/:search", departmentController.CountSearchDepartment)
		departmentGroup.GET("/:id", departmentController.FindDepartmentById)
		departmentGroup.GET("/exc/:divId/:id", departmentController.FindExcDepartment)
		departmentGroup.GET("/byDivision/:divId", departmentController.FindDepartmentByDivId)
		departmentGroup.GET("/CountDepartmentName/:search", departmentController.CountDepartmentName)
		departmentGroup.POST("/", departmentController.InsertDepartment)
		departmentGroup.PUT("/:id", departmentController.UpdateDepartment)
		departmentGroup.DELETE("/:id", departmentController.DeleteDepartment)
	}

	sectionGroup := r.Group("/api/section", middleware.AuthorizeJWT(jwtService))
	{
		sectionGroup.GET("/", sectionController.CountSectionAll)
		sectionGroup.GET("/all", sectionController.FindSections)
		sectionGroup.GET("/list/:limit/:offset/:order/:dir", sectionController.FindSectionsOffset)
		sectionGroup.GET("/search/:limit/:offset/:order/:dir/:search", sectionController.SearchSection)
		sectionGroup.GET("/countSearch/:search", sectionController.CountSearchSection)
		sectionGroup.GET("/:id", sectionController.FindSectionById)
		sectionGroup.GET("/exc/:depId/:id", sectionController.FindExcSection)
		sectionGroup.GET("/byDepartment/:depId", sectionController.FindSectionByDepId)
		sectionGroup.GET("/byDivision/:divId", sectionController.FindSectionByDivisionID)
		sectionGroup.GET("/countSectionName/:search", sectionController.CountSectionName)
		sectionGroup.POST("/", sectionController.InsertSection)
		sectionGroup.PUT("/:id", sectionController.UpdateSection)
		sectionGroup.DELETE("/:id", sectionController.DeleteSection)
	}

	positionGroup := r.Group("/api/position", middleware.AuthorizeJWT(jwtService))
	{
		positionGroup.GET("/", positionController.CountPositionAll)
		positionGroup.GET("/all", positionController.FindPositions)
		positionGroup.GET("/list/:limit/:offset/:order/:dir", positionController.FindPositionsOffset)
		positionGroup.GET("/search/:limit/:offset/:order/:dir/:search", positionController.SearchPosition)
		positionGroup.GET("/countSearch/:search", positionController.CountSearchPosition)
		positionGroup.GET("/:id", positionController.FindPositionById)
		positionGroup.GET("/exc/:id", positionController.FindExcPosition)
		positionGroup.POST("/", positionController.InsertPosition)
		positionGroup.PUT("/:id", positionController.UpdatePosition)
		positionGroup.DELETE("/:id", positionController.DeletePosition)
	}

	locationGroup := r.Group("/api/location", middleware.AuthorizeJWT(jwtService))
	{
		locationGroup.GET("/", locationController.CountLocationAll)
		locationGroup.GET("/all", locationController.FindLocations)
		locationGroup.GET("/list/:limit/:offset/:order/:dir", locationController.FindLocationsOffset)
		locationGroup.GET("/search/:limit/:offset/:order/:dir/:search", locationController.SearchLocation)
		locationGroup.GET("/countSearch/:search", locationController.CountSearchLocation)
		locationGroup.GET("/:id", locationController.FindLocationById)
		locationGroup.GET("/exc/:id", locationController.FindExcLocation)
		locationGroup.POST("/", locationController.InsertLocation)
		locationGroup.PUT("/:id", locationController.UpdateLocation)
		locationGroup.DELETE("/:id", locationController.DeleteLocation)
	}

	employeeGroup := r.Group("/api/employee", middleware.AuthorizeJWT(jwtService))
	{
		employeeGroup.GET("/", employeeController.CountEmployeeAll)
		employeeGroup.GET("/all", employeeController.FindEmployees)
		employeeGroup.GET("/list/:limit/:offset/:order/:dir", employeeController.FindEmployeesOffset)
		employeeGroup.GET("/search/:limit/:offset/:order/:dir/:search", employeeController.SearchEmployee)
		employeeGroup.GET("/countSearch/:search", employeeController.CountSearchEmployee)
		employeeGroup.GET("/:id", employeeController.FindEmployeeById)
		employeeGroup.GET("/byNik/:nik", employeeController.FindEmployeeByNik)
		employeeGroup.GET("/exc/:id", employeeController.FindExcEmployee)
		employeeGroup.GET("/byDepartment/:department", employeeController.FindEmployeeByDepartment)
		employeeGroup.GET("/byPosition/:group/:division/:department/:position", employeeController.FindEmployeeByPosition)
		employeeGroup.GET("/byDivandDep/:DivId/:DepId", employeeController.FindEmployeeByDivIdAndDepId)
		employeeGroup.GET("/byDate/:date", employeeController.FindEmployeeByDate)
		employeeGroup.GET("/cuti/:group/:section/:division/:department/:position", employeeController.FindEmployeeCuti)
		employeeGroup.POST("/", employeeController.InsertEmployee)
		employeeGroup.PUT("/:id", employeeController.UpdateEmployee)
		employeeGroup.DELETE("/:id", employeeController.DeleteEmployee)
	}

	userGroup := r.Group("/api/user", middleware.AuthorizeJWT(jwtService))
	{
		userGroup.GET("/", userController.CountUserAll)
		userGroup.GET("/all", userController.FindUsers)
		userGroup.GET("/list/:limit/:offset/:order/:dir", userController.FindUsersOffset)
		userGroup.GET("/search/:limit/:offset/:order/:dir/:search", userController.SearchUser)
		userGroup.GET("/countSearch/:search", userController.CountSearchUser)
		userGroup.GET("/:id", userController.FindUserById)
		userGroup.GET("/full/:id", userController.FindUsersAll)
		userGroup.GET("/byNUName/:uName", userController.FindUserByUName)
		userGroup.GET("/exc/:id", userController.FindExcUser)
		userGroup.POST("/", userController.InsertUser)
		userGroup.PUT("/:id", userController.UpdateUser)
		userGroup.DELETE("/:id", userController.DeleteUser)
	}

	formGroup := r.Group("/api/form", middleware.AuthorizeJWT(jwtService))
	{
		formGroup.GET("/", formController.CountFormAll)
		formGroup.GET("/all", formController.FindForms)
		formGroup.GET("/list/:limit/:offset/:order/:dir", formController.FindFormsOffset)
		formGroup.GET("/search/:limit/:offset/:order/:dir/:search", formController.SearchForm)
		formGroup.GET("/countSearch/:search", formController.CountSearchForm)
		formGroup.GET("/formJoinRole/:uId/:fpId", formController.FindFormJoinRole)
		formGroup.GET("/formByRole/:uId", formController.FindFormByRole)
		formGroup.GET("/formByType/:tyId", formController.FindFormByType)
		formGroup.GET("/excFormByType/:tyId/:id", formController.FindExcFormByType)
		formGroup.GET("/:id", formController.FindFormById)
		formGroup.GET("/formByFormTypeId/:ftId", formController.FindFormByFormTypeId)
		formGroup.GET("/excForm/:ftId/:id", formController.FindExcForm)
		formGroup.GET("/formHead/:ftId", formController.FindFormHead)
		formGroup.GET("/formHeadDetail/:id", formController.FindFormHeadDetail)
		formGroup.GET("/excFormHead/:id", formController.FindExcFormHead)
		formGroup.GET("/excFormOnly/:id", formController.FindExcFormOnly)
		formGroup.POST("/", formController.InsertForm)
		formGroup.PUT("/:id", formController.UpdateForm)
		formGroup.DELETE("/:id", formController.DeleteForm)
	}

	formTypeGroup := r.Group("/api/FormType", middleware.AuthorizeJWT(jwtService))
	{
		formTypeGroup.GET("/", formTypeController.CountFormTypeAll)
		formTypeGroup.GET("/all", formTypeController.FindFormTypes)
		formTypeGroup.GET("/list/:limit/:offset/:order/:dir", formTypeController.FindFormTypesOffset)
		formTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", formTypeController.SearchFormType)
		formTypeGroup.GET("/countSearch/:search", formTypeController.CountSearchFormType)
		formTypeGroup.GET("/:id", formTypeController.FindFormTypeById)
		formTypeGroup.GET("/exc/:id", formTypeController.FindExcFormType)
		formTypeGroup.POST("/", formTypeController.InsertFormType)
		formTypeGroup.PUT("/:id", formTypeController.UpdateFormType)
		formTypeGroup.DELETE("/:id", formTypeController.DeleteFormType)
	}

	roleGroup := r.Group("/api/role", middleware.AuthorizeJWT(jwtService))
	{
		roleGroup.GET("/", roleController.CountRoleAll)
		roleGroup.GET("/all", roleController.FindRoles)
		roleGroup.GET("/list/:limit/:offset/:order/:dir", roleController.FindRolesOffset)
		roleGroup.GET("/search/:limit/:offset/:order/:dir/:search", roleController.SearchRole)
		roleGroup.GET("/countSearch/:search", roleController.CountSearchRole)
		roleGroup.GET("/:id", roleController.FindRoleById)
		roleGroup.GET("/exc/:id", roleController.FindExcRole)
		roleGroup.POST("/", roleController.InsertRole)
		roleGroup.PUT("/:id", roleController.UpdateRole)
		roleGroup.DELETE("/:id", roleController.DeleteRole)
	}

	userRoleGroup := r.Group("/api/UserRole", middleware.AuthorizeJWT(jwtService))
	{
		userRoleGroup.GET("/count/:usernameID", userRoleController.CountUserRoleAll)
		userRoleGroup.GET("/all", userRoleController.FindUserRoles)
		userRoleGroup.GET("/list/:limit/:offset/:order/:dir/:usernameID", userRoleController.FindUserRolesOffset)
		userRoleGroup.GET("/search/:limit/:offset/:order/:dir/:search/:usernameID", userRoleController.SearchUserRole)
		userRoleGroup.GET("/countSearch/:search/:usernameID", userRoleController.CountSearchUserRole)
		userRoleGroup.GET("/:id", userRoleController.FindUserRoleById)
		userRoleGroup.GET("/byUserId/:uid", userRoleController.FindUserRoleByUserId)
		userRoleGroup.GET("/exc/:id/:uid", userRoleController.FindExcUserRole)
		userRoleGroup.GET("/excOnly/:id", userRoleController.FindExcUserRoleOnly)
		userRoleGroup.POST("/", userRoleController.InsertUserRole)
		userRoleGroup.PUT("/:id", userRoleController.UpdateUserRole)
		userRoleGroup.DELETE("/:id", userRoleController.DeleteUserRole)
	}

	roleFormGroup := r.Group("/api/RoleForm", middleware.AuthorizeJWT(jwtService))
	{
		roleFormGroup.GET("/count/:roleID", roleFormController.CountRoleFormAll)
		roleFormGroup.GET("/all", roleFormController.FindRoleForms)
		roleFormGroup.GET("/list/:limit/:offset/:order/:dir/:roleID", roleFormController.FindRoleFormsOffset)
		roleFormGroup.GET("/search/:limit/:offset/:order/:dir/:search/:roleID", roleFormController.SearchRoleForm)
		roleFormGroup.GET("/countSearch/:search/:roleID", roleFormController.CountSearchRoleForm)
		roleFormGroup.GET("/:id", roleFormController.FindRoleFormById)
		roleFormGroup.GET("/byFormId/:fid/:rid", roleFormController.FindRoleFormByFormId)
		roleFormGroup.GET("/exc/:id/:rid", roleFormController.FindExcRoleForm)
		roleFormGroup.GET("/excOnly/:id", roleFormController.FindExcRoleFormOnly)
		roleFormGroup.POST("/", roleFormController.InsertRoleForm)
		roleFormGroup.PUT("/:id", roleFormController.UpdateRoleForm)
		roleFormGroup.DELETE("/:id", roleFormController.DeleteRoleForm)
	}

	businessUnitGroup := r.Group("/api/BusinessUnit", middleware.AuthorizeJWT(jwtService))
	{
		businessUnitGroup.GET("/", businessUnitController.CountBusinessUnitAll)
		businessUnitGroup.GET("/all", businessUnitController.FindBusinessUnits)
		businessUnitGroup.GET("/list/:limit/:offset/:order/:dir", businessUnitController.FindBusinessUnitsOffset)
		businessUnitGroup.GET("/search/:limit/:offset/:order/:dir/:search", businessUnitController.SearchBusinessUnit)
		businessUnitGroup.GET("/countSearch/:search", businessUnitController.CountSearchBusinessUnit)
		businessUnitGroup.GET("/:id", businessUnitController.FindBusinessUnitById)
		businessUnitGroup.GET("/exc/:id", businessUnitController.FindExcBusinessUnit)
		businessUnitGroup.POST("/", businessUnitController.InsertBusinessUnit)
		businessUnitGroup.PUT("/:id", businessUnitController.UpdateBusinessUnit)
		businessUnitGroup.DELETE("/:id", businessUnitController.DeleteBusinessUnit)
	}

	companyManagementTypeGroup := r.Group("/api/CompanyManagementType", middleware.AuthorizeJWT(jwtService))
	{
		companyManagementTypeGroup.GET("/", companyManagementTypeController.CountCompanyManagementTypeAll)
		companyManagementTypeGroup.GET("/all", companyManagementTypeController.FindCompanyManagementTypes)
		companyManagementTypeGroup.GET("/list/:limit/:offset/:order/:dir", companyManagementTypeController.FindCompanyManagementTypesOffset)
		companyManagementTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", companyManagementTypeController.SearchCompanyManagementType)
		companyManagementTypeGroup.GET("/countSearch/:search", companyManagementTypeController.CountSearchCompanyManagementType)
		companyManagementTypeGroup.GET("/:id", companyManagementTypeController.FindCompanyManagementTypeById)
		companyManagementTypeGroup.GET("/exc/:id", companyManagementTypeController.FindExcCompanyManagementType)
		companyManagementTypeGroup.POST("/", companyManagementTypeController.InsertCompanyManagementType)
		companyManagementTypeGroup.PUT("/:id", companyManagementTypeController.UpdateCompanyManagementType)
		companyManagementTypeGroup.DELETE("/:id", companyManagementTypeController.DeleteCompanyManagementType)
	}

	licenseTypeGroup := r.Group("/api/LicenseType", middleware.AuthorizeJWT(jwtService))
	{
		licenseTypeGroup.GET("/", licenseTypeController.CountLicenseTypeAll)
		licenseTypeGroup.GET("/all", licenseTypeController.FindLicenseTypes)
		licenseTypeGroup.GET("/list/:limit/:offset/:order/:dir", licenseTypeController.FindLicenseTypesOffset)
		licenseTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", licenseTypeController.SearchLicenseType)
		licenseTypeGroup.GET("/countSearch/:search", licenseTypeController.CountSearchLicenseType)
		licenseTypeGroup.GET("/:id", licenseTypeController.FindLicenseTypeById)
		licenseTypeGroup.GET("/exc/:id", licenseTypeController.FindExcLicenseType)
		licenseTypeGroup.GET("/excComplete/:groupLT/:id", licenseTypeController.FindExcCompleteLicenseType)
		licenseTypeGroup.GET("/byGroupLicenseType/:groupLT", licenseTypeController.FindLicenseTypeByGroupLT)
		licenseTypeGroup.POST("/", licenseTypeController.InsertLicenseType)
		licenseTypeGroup.PUT("/:id", licenseTypeController.UpdateLicenseType)
		licenseTypeGroup.DELETE("/:id", licenseTypeController.DeleteLicenseType)
	}

	emailQueueTypeGroup := r.Group("/api/EmailQueueType", middleware.AuthorizeJWT(jwtService))
	{
		emailQueueTypeGroup.GET("/", emailQueueTypeController.CountEmailQueueTypeAll)
		emailQueueTypeGroup.GET("/all", emailQueueTypeController.FindEmailQueueTypes)
		emailQueueTypeGroup.GET("/list/:limit/:offset/:order/:dir", emailQueueTypeController.FindEmailQueueTypesOffset)
		emailQueueTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", emailQueueTypeController.SearchEmailQueueType)
		emailQueueTypeGroup.GET("/countSearch/:search", emailQueueTypeController.CountSearchEmailQueueType)
		emailQueueTypeGroup.GET("/:id", emailQueueTypeController.FindEmailQueueTypeById)
		emailQueueTypeGroup.GET("/exc/:id", emailQueueTypeController.FindExcEmailQueueType)
		emailQueueTypeGroup.POST("/", emailQueueTypeController.InsertEmailQueueType)
		emailQueueTypeGroup.PUT("/:id", emailQueueTypeController.UpdateEmailQueueType)
		emailQueueTypeGroup.DELETE("/:id", emailQueueTypeController.DeleteEmailQueueType)
	}

	emailQueueGroup := r.Group("/api/EmailQueue", middleware.AuthorizeJWT(jwtService))
	{
		emailQueueGroup.GET("/", emailQueueController.CountEmailQueueAll)
		emailQueueGroup.GET("/all", emailQueueController.FindEmailQueues)
		emailQueueGroup.GET("/list/:limit/:offset/:order/:dir", emailQueueController.FindEmailQueuesOffset)
		emailQueueGroup.GET("/search/:limit/:offset/:order/:dir/:search", emailQueueController.SearchEmailQueue)
		emailQueueGroup.GET("/countSearch/:search", emailQueueController.CountSearchEmailQueue)
		emailQueueGroup.GET("/:id", emailQueueController.FindEmailQueueById)
		emailQueueGroup.GET("/byStatus/:status", emailQueueController.FindEmailQueueByStatus)
		emailQueueGroup.GET("/exc/:id", emailQueueController.FindExcEmailQueue)
		emailQueueGroup.POST("/", emailQueueController.InsertEmailQueue)
		emailQueueGroup.PUT("/:id", emailQueueController.UpdateEmailQueue)
		emailQueueGroup.DELETE("/:id", emailQueueController.DeleteEmailQueue)
	}

	emailQueueReferenceGroup := r.Group("/api/EmailQueueReference", middleware.AuthorizeJWT(jwtService))
	{
		emailQueueReferenceGroup.GET("/", emailQueueReferenceController.CountEmailQueueReferenceAll)
		emailQueueReferenceGroup.GET("/all", emailQueueReferenceController.FindEmailQueueReferences)
		emailQueueReferenceGroup.GET("/list/:limit/:offset/:order/:dir", emailQueueReferenceController.FindEmailQueueReferencesOffset)
		emailQueueReferenceGroup.GET("/search/:limit/:offset/:order/:dir/:search", emailQueueReferenceController.SearchEmailQueueReference)
		emailQueueReferenceGroup.GET("/countSearch/:search", emailQueueReferenceController.CountSearchEmailQueueReference)
		emailQueueReferenceGroup.GET("/:id", emailQueueReferenceController.FindEmailQueueReferenceById)
		emailQueueReferenceGroup.GET("/exc/:id", emailQueueReferenceController.FindExcEmailQueueReference)
		emailQueueReferenceGroup.POST("/", emailQueueReferenceController.InsertEmailQueueReference)
		emailQueueReferenceGroup.PUT("/:id", emailQueueReferenceController.UpdateEmailQueueReference)
		emailQueueReferenceGroup.DELETE("/:id", emailQueueReferenceController.DeleteEmailQueueReference)
	}

	companyGroup := r.Group("/api/company", middleware.AuthorizeJWT(jwtService))
	{
		companyGroup.GET("/", companyController.CountCompanyAll)
		companyGroup.GET("/all", companyController.FindCompanys)
		companyGroup.GET("/allFilter/:companyID", companyController.FindCompanyFilters)
		companyGroup.GET("/list/:limit/:offset/:order/:dir/:companyID", companyController.FindCompanysOffset)
		companyGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyID", companyController.SearchCompany)
		companyGroup.GET("/countSearch/:search/:companyID", companyController.CountSearchCompany)
		companyGroup.GET("/app/count/:companyId", companyController.CountCompanyApprove)
		companyGroup.GET("/app/:limit/:offset/:order/:dir/:companyId", companyController.FindCompanyApprove)
		companyGroup.GET("/app/search/:limit/:offset/:order/:dir/:search/:companyId", companyController.SearchCompanyApprove)
		companyGroup.GET("/app/countSearch/:search/:companyId", companyController.CountSearchCompanyApprove)
		companyGroup.GET("/:id", companyController.FindCompanyById)
		companyGroup.GET("/exc/:id", companyController.FindExcCompany)
		companyGroup.POST("/", companyController.InsertCompany)
		companyGroup.PUT("/:id", companyController.UpdateCompany)
		companyGroup.PUT("/approved/:id", companyController.UpdateCompanyApprove)
		companyGroup.PUT("/deactived/:id", companyController.UpdateCompanyDeactive)
		companyGroup.DELETE("/:id", companyController.DeleteCompany)
	}

	companyShareholderGroup := r.Group("/api/companyShareholder", middleware.AuthorizeJWT(jwtService))
	{
		companyShareholderGroup.GET("/count/:companyId", companyShareholderController.CountCompanyShareholderAll)
		companyShareholderGroup.GET("/all/:companyId", companyShareholderController.FindCompanyShareholders)
		companyShareholderGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", companyShareholderController.FindCompanyShareholdersOffset)
		companyShareholderGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", companyShareholderController.SearchCompanyShareholder)
		companyShareholderGroup.GET("/countSearch/:search/:companyId", companyShareholderController.CountSearchCompanyShareholder)
		companyShareholderGroup.GET("/byCompany/:id", companyShareholderController.FindCompanyShareholderByCompanyId)
		companyShareholderGroup.GET("/:id", companyShareholderController.FindCompanyShareholderById)
		companyShareholderGroup.GET("/exc/:id", companyShareholderController.FindExcCompanyShareholder)
		companyShareholderGroup.POST("/", companyShareholderController.InsertCompanyShareholder)
		companyShareholderGroup.PUT("/:id", companyShareholderController.UpdateCompanyShareholder)
		companyShareholderGroup.DELETE("/:id", companyShareholderController.DeleteCompanyShareholder)
	}

	companyManagementGroup := r.Group("/api/companyManagement", middleware.AuthorizeJWT(jwtService))
	{
		companyManagementGroup.GET("/count/:companyId", companyManagementController.CountCompanyManagementAll)
		companyManagementGroup.GET("/all/:companyId", companyManagementController.FindCompanyManagements)
		companyManagementGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", companyManagementController.FindCompanyManagementsOffset)
		companyManagementGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", companyManagementController.SearchCompanyManagement)
		companyManagementGroup.GET("/countSearch/:search/:companyId", companyManagementController.CountSearchCompanyManagement)
		companyManagementGroup.GET("/:id", companyManagementController.FindCompanyManagementById)
		companyManagementGroup.GET("/exc/:id", companyManagementController.FindExcCompanyManagement)
		companyManagementGroup.GET("/byCompany/:id", companyManagementController.FindCompanyManagementByCompanyId)
		companyManagementGroup.POST("/", companyManagementController.InsertCompanyManagement)
		companyManagementGroup.PUT("/:id", companyManagementController.UpdateCompanyManagement)
		companyManagementGroup.DELETE("/:id", companyManagementController.DeleteCompanyManagement)
	}

	companyLicenseGroup := r.Group("/api/companyLicense", middleware.AuthorizeJWT(jwtService))
	{
		companyLicenseGroup.GET("/byCompany/:id", companyLicenseController.FindCompanyLicenseByCompanyId)
		companyLicenseGroup.GET("/count/:companyId/:licenseGroup", companyLicenseController.CountCompanyLicenseAll)
		companyLicenseGroup.GET("/all", companyLicenseController.FindCompanyLicenses)
		companyLicenseGroup.GET("/list/:limit/:offset/:order/:dir/:companyId/:licenseGroup", companyLicenseController.FindCompanyLicensesOffset)
		companyLicenseGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId/:licenseGroup", companyLicenseController.SearchCompanyLicense)
		companyLicenseGroup.GET("/countSearch/:search/:companyId/:licenseGroup", companyLicenseController.CountSearchCompanyLicense)
		companyLicenseGroup.GET("/mobile/count/:companyId/", companyLicenseController.CountCompanyLicenseAllMobile)
		companyLicenseGroup.GET("/mobile/list/:limit/:offset/:order/:dir/:companyId/", companyLicenseController.FindCompanyLicensesOffsetMobile)
		companyLicenseGroup.GET("/mobile/search/:limit/:offset/:order/:dir/:search/:companyId/", companyLicenseController.SearchCompanyLicenseMobile)
		companyLicenseGroup.GET("/mobile/countSearch/:search/:companyId/", companyLicenseController.CountSearchCompanyLicenseMobile)
		companyLicenseGroup.GET("/app/count/:companyId", companyLicenseController.CountCompanyLicenseApp)
		companyLicenseGroup.GET("/app/:limit/:offset/:order/:dir/:companyId", companyLicenseController.FindCompanyLicensesApp)
		companyLicenseGroup.GET("/app/search/:limit/:offset/:order/:dir/:search/:companyId", companyLicenseController.SearchCompanyLicenseApp)
		companyLicenseGroup.GET("/app/countSearch/:search/:companyId", companyLicenseController.CountSearchCompanyLicenseApp)
		companyLicenseGroup.GET("/exp/count/:companyId", companyLicenseController.CountExpCompanyLicense)
		companyLicenseGroup.GET("/exp/:limit/:offset/:order/:dir/:companyId", companyLicenseController.FindExpCompanyLicenses)
		companyLicenseGroup.GET("/exp/search/:limit/:offset/:order/:dir/:search/:companyId", companyLicenseController.SearchExpCompanyLicense)
		companyLicenseGroup.GET("/exp/countSearch/:search/:companyId", companyLicenseController.CountSearchExpCompanyLicense)
		companyLicenseGroup.GET("/:id", companyLicenseController.FindCompanyLicenseById)
		companyLicenseGroup.GET("/exc/:id", companyLicenseController.FindExcCompanyLicense)
		companyLicenseGroup.GET("/countFull/:companyId", companyLicenseController.CountCompanyLicenseFull)
		companyLicenseGroup.GET("/listFull/:limit/:offset/:order/:dir/:companyId", companyLicenseController.FindCompanyLicensesOffsetFull)
		companyLicenseGroup.GET("/searchFull/:limit/:offset/:order/:dir/:search/:companyId", companyLicenseController.SearchCompanyLicenseFull)
		companyLicenseGroup.GET("/countSearchFull/:search/:companyId", companyLicenseController.CountSearchCompanyLicenseFull)
		companyLicenseGroup.POST("/", companyLicenseController.InsertCompanyLicense)
		companyLicenseGroup.PUT("/:id", companyLicenseController.UpdateCompanyLicense)
		companyLicenseGroup.PUT("/status/:id", companyLicenseController.UpdateCompanyLicenseStatus)
		companyLicenseGroup.PUT("/statusDeactive/:id", companyLicenseController.UpdateCompanyLicenseDeactive)
		companyLicenseGroup.PUT("/renewal/:id", companyLicenseController.UpdateCompanyLicenseApprovedRenewalStatus)
		companyLicenseGroup.PUT("/remark/:id", companyLicenseController.UpdateCompanyRemark)
		companyLicenseGroup.DELETE("/:id", companyLicenseController.DeleteCompanyLicense)
	}

	companyLicenseRenewalTracingGroup := r.Group("/api/CompanyLicenseRenewalTracing", middleware.AuthorizeJWT(jwtService))
	{
		companyLicenseRenewalTracingGroup.GET("/", companyLicenseRenewalTracingController.FindCompanyLicenseRenewalTracings)
		companyLicenseRenewalTracingGroup.GET("/:id", companyLicenseRenewalTracingController.FindCompanyLicenseRenewalTracingById)
		companyLicenseRenewalTracingGroup.GET("/exc/:id", companyLicenseRenewalTracingController.FindExcCompanyLicenseRenewalTracing)
		companyLicenseRenewalTracingGroup.POST("/", companyLicenseRenewalTracingController.InsertCompanyLicenseRenewalTracing)
		companyLicenseRenewalTracingGroup.PUT("/:id", companyLicenseRenewalTracingController.UpdateCompanyLicenseRenewalTracing)
		companyLicenseRenewalTracingGroup.DELETE("/:id", companyLicenseRenewalTracingController.DeleteCompanyLicenseRenewalTracing)
	}

	usercompanyrestrictionGroup := r.Group("/api/userCompanyRestriction", middleware.AuthorizeJWT(jwtService))
	{
		usercompanyrestrictionGroup.GET("/count/:usernameID", userCompanyRestrictionController.CountUserCompanyRestrictionAll)
		usercompanyrestrictionGroup.GET("/all", userCompanyRestrictionController.FindUserCompanyRestrictions)
		usercompanyrestrictionGroup.GET("/list/:limit/:offset/:order/:dir/:usernameID", userCompanyRestrictionController.FindUserCompanyRestrictionsOffset)
		usercompanyrestrictionGroup.GET("/search/:limit/:offset/:order/:dir/:search/:usernameID", userCompanyRestrictionController.SearchUserCompanyRestriction)
		usercompanyrestrictionGroup.GET("/countSearch/:search/:usernameID", userCompanyRestrictionController.CountSearchUserCompanyRestriction)
		usercompanyrestrictionGroup.GET("/:id", userCompanyRestrictionController.FindUserCompanyRestrictionById)
		usercompanyrestrictionGroup.GET("/user/:uid", userCompanyRestrictionController.FindUserCompanyRestrictionByUserId)
		usercompanyrestrictionGroup.GET("/exc/:id", userCompanyRestrictionController.FindExcUserCompanyRestriction)
		usercompanyrestrictionGroup.POST("/", userCompanyRestrictionController.InsertUserCompanyRestriction)
		usercompanyrestrictionGroup.PUT("/:id", userCompanyRestrictionController.UpdateUserCompanyRestriction)
		usercompanyrestrictionGroup.DELETE("/:id", userCompanyRestrictionController.DeleteUserCompanyRestriction)
	}

	companyGroupGroup := r.Group("/api/CompanyGroup", middleware.AuthorizeJWT(jwtService))
	{
		companyGroupGroup.GET("/", companyGroupController.CountCompanyGroupAll)
		companyGroupGroup.GET("/all", companyGroupController.FindCompanyGroups)
		companyGroupGroup.GET("/list/:limit/:offset/:order/:dir", companyGroupController.FindCompanyGroupsOffset)
		companyGroupGroup.GET("/search/:limit/:offset/:order/:dir/:search", companyGroupController.SearchCompanyGroup)
		companyGroupGroup.GET("/countSearch/:search", companyGroupController.CountSearchCompanyGroup)
		companyGroupGroup.GET("/:id", companyGroupController.FindCompanyGroupById)
		companyGroupGroup.GET("/exc/:id", companyGroupController.FindExcCompanyGroup)
		companyGroupGroup.POST("/", companyGroupController.InsertCompanyGroup)
		companyGroupGroup.PUT("/:id", companyGroupController.UpdateCompanyGroup)
		companyGroupGroup.DELETE("/:id", companyGroupController.DeleteCompanyGroup)
	}

	companyGroupCompanyGroup := r.Group("/api/companyGroupCompany", middleware.AuthorizeJWT(jwtService))
	{
		companyGroupCompanyGroup.GET("/count/:companyGroupID", companyGroupCompanyController.CountCompanyGroupCompanyAll)
		companyGroupCompanyGroup.GET("/all/byCompany/:companyID", companyGroupCompanyController.FindCompanyGroupCompanysByCompanyID)
		companyGroupCompanyGroup.GET("/all/:companyGroupID", companyGroupCompanyController.FindCompanyGroupCompanys)
		companyGroupCompanyGroup.GET("/list/:limit/:offset/:order/:dir/:companyGroupID", companyGroupCompanyController.FindCompanyGroupCompanysOffset)
		companyGroupCompanyGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyGroupID", companyGroupCompanyController.SearchCompanyGroupCompany)
		companyGroupCompanyGroup.GET("/countSearch/:search/:companyGroupID", companyGroupCompanyController.CountSearchCompanyGroupCompany)
		companyGroupCompanyGroup.GET("/:id", companyGroupCompanyController.FindCompanyGroupCompanyById)
		companyGroupCompanyGroup.POST("/", companyGroupCompanyController.InsertCompanyGroupCompany)
		companyGroupCompanyGroup.PUT("/:id", companyGroupCompanyController.UpdateCompanyGroupCompany)
		companyGroupCompanyGroup.DELETE("/:id", companyGroupCompanyController.DeleteCompanyGroupCompany)
	}

	groupLicenseTypeGroup := r.Group("/api/GroupLicenseType", middleware.AuthorizeJWT(jwtService))
	{
		groupLicenseTypeGroup.GET("/", groupLicenseTypeController.CountGroupLicenseTypeAll)
		groupLicenseTypeGroup.GET("/all", groupLicenseTypeController.FindGroupLicenseTypes)
		groupLicenseTypeGroup.GET("/list/:limit/:offset/:order/:dir", groupLicenseTypeController.FindGroupLicenseTypesOffset)
		groupLicenseTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", groupLicenseTypeController.SearchGroupLicenseType)
		groupLicenseTypeGroup.GET("/countSearch/:search", groupLicenseTypeController.CountSearchGroupLicenseType)
		groupLicenseTypeGroup.GET("/:id", groupLicenseTypeController.FindGroupLicenseTypeById)
		groupLicenseTypeGroup.GET("/exc/:id", groupLicenseTypeController.FindExcGroupLicenseType)
		groupLicenseTypeGroup.POST("/", groupLicenseTypeController.InsertGroupLicenseType)
		groupLicenseTypeGroup.PUT("/:id", groupLicenseTypeController.UpdateGroupLicenseType)
		groupLicenseTypeGroup.DELETE("/:id", groupLicenseTypeController.DeleteGroupLicenseType)
	}

	internalMemoTypeGroup := r.Group("/api/InternalMemoType", middleware.AuthorizeJWT(jwtService))
	{
		internalMemoTypeGroup.GET("/", internalMemoTypeController.CountInternalMemoTypeAll)
		internalMemoTypeGroup.GET("/all", internalMemoTypeController.FindInternalMemoTypes)
		internalMemoTypeGroup.GET("/list/:limit/:offset/:order/:dir", internalMemoTypeController.FindInternalMemoTypesOffset)
		internalMemoTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", internalMemoTypeController.SearchInternalMemoType)
		internalMemoTypeGroup.GET("/countSearch/:search", internalMemoTypeController.CountSearchInternalMemoType)
		internalMemoTypeGroup.GET("/:id", internalMemoTypeController.FindInternalMemoTypeById)
		internalMemoTypeGroup.GET("/exc/:id", internalMemoTypeController.FindExcInternalMemoType)
		internalMemoTypeGroup.POST("/", internalMemoTypeController.InsertInternalMemoType)
		internalMemoTypeGroup.PUT("/:id", internalMemoTypeController.UpdateInternalMemoType)
		internalMemoTypeGroup.DELETE("/:id", internalMemoTypeController.DeleteInternalMemoType)
	}

	internalMemoGroup := r.Group("/api/internalMemo", middleware.AuthorizeJWT(jwtService))
	{
		internalMemoGroup.GET("/count/:employeeID", internalMemoController.CountInternalMemoAll)
		internalMemoGroup.GET("/all", internalMemoController.FindInternalMemos)
		internalMemoGroup.GET("/list/:limit/:offset/:order/:dir/:employeeID", internalMemoController.FindInternalMemosOffset)
		internalMemoGroup.GET("/search/:limit/:offset/:order/:dir/:search/:employeeID", internalMemoController.SearchInternalMemo)
		internalMemoGroup.GET("/countSearch/:search/:employeeID", internalMemoController.CountSearchInternalMemo)
		internalMemoGroup.GET("/countByDept/:deptName", internalMemoController.CountInternalMemoByDept)
		internalMemoGroup.GET("/:id", internalMemoController.FindInternalMemoById)
		internalMemoGroup.GET("/exc/:id", internalMemoController.FindExcInternalMemo)
		internalMemoGroup.POST("/", internalMemoController.InsertInternalMemo)
		internalMemoGroup.PUT("/:id", internalMemoController.UpdateInternalMemo)
		internalMemoGroup.PUT("/approved/:id", internalMemoController.UpdateInternalMemoApprove)
		internalMemoGroup.PUT("/uploadDoc/:id", internalMemoController.UploadIMDocument)
		internalMemoGroup.DELETE("/:id", internalMemoController.DeleteInternalMemo)
	}

	internalMemoCirculationGroup := r.Group("/api/internalMemoCirculation", middleware.AuthorizeJWT(jwtService))
	{
		internalMemoCirculationGroup.GET("/count/:internalMemoId", internalMemoCirculationController.CountInternalMemoCirculationAll)
		internalMemoCirculationGroup.GET("/all/:internalMemoId", internalMemoCirculationController.FindInternalMemoCirculations)
		internalMemoCirculationGroup.GET("/stat/:internalMemoId/:cirStat", internalMemoCirculationController.FindInternalMemoCirculationStat)
		internalMemoCirculationGroup.GET("/listStat/:internalMemoId/:cirStat", internalMemoCirculationController.FindInternalMemoCirculationListStat)
		internalMemoCirculationGroup.GET("/seq/:internalMemoId/:employeeID", internalMemoCirculationController.FindInternalMemoCirculationSeq)
		internalMemoCirculationGroup.GET("/list/:limit/:offset/:order/:dir/:internalMemoId", internalMemoCirculationController.FindInternalMemoCirculationsOffset)
		internalMemoCirculationGroup.GET("/search/:limit/:offset/:order/:dir/:search/:internalMemoId", internalMemoCirculationController.SearchInternalMemoCirculation)
		internalMemoCirculationGroup.GET("/countSearch/:search/:internalMemoId", internalMemoCirculationController.CountSearchInternalMemoCirculation)
		internalMemoCirculationGroup.GET("/:id", internalMemoCirculationController.FindInternalMemoCirculationById)
		internalMemoCirculationGroup.GET("/exc/:id", internalMemoCirculationController.FindExcInternalMemoCirculation)
		internalMemoCirculationGroup.GET("/byCompany/:id", internalMemoCirculationController.FindInternalMemoCirculationByCompanyId)
		internalMemoCirculationGroup.POST("/", internalMemoCirculationController.InsertInternalMemoCirculation)
		internalMemoCirculationGroup.PUT("/:id", internalMemoCirculationController.UpdateInternalMemoCirculation)
		internalMemoCirculationGroup.PUT("/approved/:id", internalMemoCirculationController.UpdateInternalMemoCirculationApprove)
		internalMemoCirculationGroup.DELETE("/:id", internalMemoCirculationController.DeleteInternalMemoCirculation)
		internalMemoCirculationGroup.GET("/countJoinIM/:employeeID", internalMemoCirculationController.CountInternalMemoCirculationJoinIM)
		internalMemoCirculationGroup.GET("/listJoinIM/:limit/:offset/:order/:dir/:employeeID", internalMemoCirculationController.FindInternalMemoCirculationsJoinIMOffset)
		internalMemoCirculationGroup.GET("/searchJoinIM/:limit/:offset/:order/:dir/:search/:employeeID", internalMemoCirculationController.SearchInternalMemoCirculationJoinIM)
		internalMemoCirculationGroup.GET("/countSearchJoinIM/:search/:employeeID", internalMemoCirculationController.CountSearchInternalMemoCirculationJoinIM)
	}

	internalMemoAttachmentGroup := r.Group("/api/internalMemoAttachment", middleware.AuthorizeJWT(jwtService))
	{
		internalMemoAttachmentGroup.GET("/count/:internalMemoId", internalMemoAttachmentController.CountInternalMemoAttachmentAll)
		internalMemoAttachmentGroup.GET("/all/:internalMemoId", internalMemoAttachmentController.FindInternalMemoAttachments)
		internalMemoAttachmentGroup.GET("/list/:limit/:offset/:order/:dir/:internalMemoId", internalMemoAttachmentController.FindInternalMemoAttachmentsOffset)
		internalMemoAttachmentGroup.GET("/search/:limit/:offset/:order/:dir/:search/:internalMemoId", internalMemoAttachmentController.SearchInternalMemoAttachment)
		internalMemoAttachmentGroup.GET("/countSearch/:search/:internalMemoId", internalMemoAttachmentController.CountSearchInternalMemoAttachment)
		internalMemoAttachmentGroup.GET("/:id", internalMemoAttachmentController.FindInternalMemoAttachmentById)
		internalMemoAttachmentGroup.GET("/exc/:id", internalMemoAttachmentController.FindExcInternalMemoAttachment)
		internalMemoAttachmentGroup.GET("/byCompany/:id", internalMemoAttachmentController.FindInternalMemoAttachmentByCompanyId)
		internalMemoAttachmentGroup.POST("/", internalMemoAttachmentController.InsertInternalMemoAttachment)
		internalMemoAttachmentGroup.PUT("/:id", internalMemoAttachmentController.UpdateInternalMemoAttachment)
		internalMemoAttachmentGroup.DELETE("/:id", internalMemoAttachmentController.DeleteInternalMemoAttachment)
	}

	internalMemoTracingGroup := r.Group("/api/InternalMemoTracing", middleware.AuthorizeJWT(jwtService))
	{
		internalMemoTracingGroup.GET("/count/:internalMemoId", internalMemoTracingController.CountInternalMemoTracingAll)
		internalMemoTracingGroup.GET("/all/:internalMemoId", internalMemoTracingController.FindInternalMemoTracings)
		internalMemoTracingGroup.GET("/:id", internalMemoTracingController.FindInternalMemoTracingById)
		internalMemoTracingGroup.GET("/exc/:id", internalMemoTracingController.FindExcInternalMemoTracing)
		internalMemoTracingGroup.POST("/", internalMemoTracingController.InsertInternalMemoTracing)
		internalMemoTracingGroup.PUT("/:id", internalMemoTracingController.UpdateInternalMemoTracing)
		internalMemoTracingGroup.DELETE("/:id", internalMemoTracingController.DeleteInternalMemoTracing)
	}

	imDefaultCirculationGroup := r.Group("/api/ImDefaultCirculation", middleware.AuthorizeJWT(jwtService))
	{
		imDefaultCirculationGroup.GET("/count/:companyGroupID", imDefaultCirculationController.CountImDefaultCirculationAll)
		imDefaultCirculationGroup.GET("/all/:companyGroupID", imDefaultCirculationController.FindImDefaultCirculations)
		imDefaultCirculationGroup.GET("/list/:limit/:offset/:order/:dir/:companyGroupID", imDefaultCirculationController.FindImDefaultCirculationsOffset)
		imDefaultCirculationGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyGroupID", imDefaultCirculationController.SearchImDefaultCirculation)
		imDefaultCirculationGroup.GET("/countSearch/:search/:companyGroupID", imDefaultCirculationController.CountSearchImDefaultCirculation)
		imDefaultCirculationGroup.GET("/:id", imDefaultCirculationController.FindImDefaultCirculationById)
		imDefaultCirculationGroup.GET("/exc/:id", imDefaultCirculationController.FindExcImDefaultCirculation)
		imDefaultCirculationGroup.POST("/", imDefaultCirculationController.InsertImDefaultCirculation)
		imDefaultCirculationGroup.PUT("/:id", imDefaultCirculationController.UpdateImDefaultCirculation)
		imDefaultCirculationGroup.DELETE("/:id", imDefaultCirculationController.DeleteImDefaultCirculation)
	}

	vehicleCategoryGroup := r.Group("/api/VehicleCategory", middleware.AuthorizeJWT(jwtService))
	{
		vehicleCategoryGroup.GET("/", vehicleCategoryController.CountVehicleCategoryAll)
		vehicleCategoryGroup.GET("/all", vehicleCategoryController.FindVehicleCategorys)
		vehicleCategoryGroup.GET("/list/:limit/:offset/:order/:dir", vehicleCategoryController.FindVehicleCategorysOffset)
		vehicleCategoryGroup.GET("/search/:limit/:offset/:order/:dir/:search", vehicleCategoryController.SearchVehicleCategory)
		vehicleCategoryGroup.GET("/countSearch/:search", vehicleCategoryController.CountSearchVehicleCategory)
		vehicleCategoryGroup.GET("/:id", vehicleCategoryController.FindVehicleCategoryById)
		vehicleCategoryGroup.GET("/exc/:id", vehicleCategoryController.FindExcVehicleCategory)
		vehicleCategoryGroup.POST("/", vehicleCategoryController.InsertVehicleCategory)
		vehicleCategoryGroup.PUT("/:id", vehicleCategoryController.UpdateVehicleCategory)
		vehicleCategoryGroup.DELETE("/:id", vehicleCategoryController.DeleteVehicleCategory)
	}

	vehicleMerkGroup := r.Group("/api/VehicleMerk", middleware.AuthorizeJWT(jwtService))
	{
		vehicleMerkGroup.GET("/", vehicleMerkController.CountVehicleMerkAll)
		vehicleMerkGroup.GET("/all", vehicleMerkController.FindVehicleMerks)
		vehicleMerkGroup.GET("/list/:limit/:offset/:order/:dir", vehicleMerkController.FindVehicleMerksOffset)
		vehicleMerkGroup.GET("/search/:limit/:offset/:order/:dir/:search", vehicleMerkController.SearchVehicleMerk)
		vehicleMerkGroup.GET("/countSearch/:search", vehicleMerkController.CountSearchVehicleMerk)
		vehicleMerkGroup.GET("/:id", vehicleMerkController.FindVehicleMerkById)
		vehicleMerkGroup.GET("/exc/:id", vehicleMerkController.FindExcVehicleMerk)
		vehicleMerkGroup.POST("/", vehicleMerkController.InsertVehicleMerk)
		vehicleMerkGroup.PUT("/:id", vehicleMerkController.UpdateVehicleMerk)
		vehicleMerkGroup.DELETE("/:id", vehicleMerkController.DeleteVehicleMerk)
	}

	vehicleTypeGroup := r.Group("/api/VehicleType", middleware.AuthorizeJWT(jwtService))
	{
		vehicleTypeGroup.GET("/", vehicleTypeController.CountVehicleTypeAll)
		vehicleTypeGroup.GET("/all", vehicleTypeController.FindVehicleTypes)
		vehicleTypeGroup.GET("/list/:limit/:offset/:order/:dir", vehicleTypeController.FindVehicleTypesOffset)
		vehicleTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", vehicleTypeController.SearchVehicleType)
		vehicleTypeGroup.GET("/countSearch/:search", vehicleTypeController.CountSearchVehicleType)
		vehicleTypeGroup.GET("/:id", vehicleTypeController.FindVehicleTypeById)
		vehicleTypeGroup.GET("/exc/:id", vehicleTypeController.FindExcVehicleType)
		vehicleTypeGroup.POST("/", vehicleTypeController.InsertVehicleType)
		vehicleTypeGroup.PUT("/:id", vehicleTypeController.UpdateVehicleType)
		vehicleTypeGroup.DELETE("/:id", vehicleTypeController.DeleteVehicleType)
	}

	vehicleGroup := r.Group("/api/vehicle", middleware.AuthorizeJWT(jwtService))
	{
		vehicleGroup.GET("/count/:companyId", vehicleController.CountVehicleAll)
		vehicleGroup.GET("/all/:companyId", vehicleController.FindVehicles)
		vehicleGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", vehicleController.FindVehiclesOffset)
		vehicleGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", vehicleController.SearchVehicle)
		vehicleGroup.GET("/countSearch/:search/:companyId", vehicleController.CountSearchVehicle)
		vehicleGroup.GET("/:id", vehicleController.FindVehicleById)
		vehicleGroup.GET("/exc/:id", vehicleController.FindExcVehicle)
		vehicleGroup.GET("/byCompany/:id", vehicleController.FindVehicleByCompanyId)
		vehicleGroup.POST("/", vehicleController.InsertVehicle)
		vehicleGroup.PUT("/:id", vehicleController.UpdateVehicle)
		vehicleGroup.DELETE("/:id", vehicleController.DeleteVehicle)
		vehicleGroup.GET("/countFull/", vehicleController.CountVehicleFull)
		vehicleGroup.GET("/listFull/:limit/:offset/:order/:dir/", vehicleController.FindVehiclesOffsetFull)
		vehicleGroup.GET("/searchFull/:limit/:offset/:order/:dir/:search/", vehicleController.SearchVehicleFull)
		vehicleGroup.GET("/countSearchFull/:search/", vehicleController.CountSearchVehicleFull)
	}

	vehicleLicenseTypeGroup := r.Group("/api/VehicleLicenseType", middleware.AuthorizeJWT(jwtService))
	{
		vehicleLicenseTypeGroup.GET("/", vehicleLicenseTypeController.CountVehicleLicenseTypeAll)
		vehicleLicenseTypeGroup.GET("/all", vehicleLicenseTypeController.FindVehicleLicenseTypes)
		vehicleLicenseTypeGroup.GET("/list/:limit/:offset/:order/:dir", vehicleLicenseTypeController.FindVehicleLicenseTypesOffset)
		vehicleLicenseTypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", vehicleLicenseTypeController.SearchVehicleLicenseType)
		vehicleLicenseTypeGroup.GET("/countSearch/:search", vehicleLicenseTypeController.CountSearchVehicleLicenseType)
		vehicleLicenseTypeGroup.GET("/:id", vehicleLicenseTypeController.FindVehicleLicenseTypeById)
		vehicleLicenseTypeGroup.GET("/exc/:id", vehicleLicenseTypeController.FindExcVehicleLicenseType)
		vehicleLicenseTypeGroup.POST("/", vehicleLicenseTypeController.InsertVehicleLicenseType)
		vehicleLicenseTypeGroup.PUT("/:id", vehicleLicenseTypeController.UpdateVehicleLicenseType)
		vehicleLicenseTypeGroup.DELETE("/:id", vehicleLicenseTypeController.DeleteVehicleLicenseType)
	}

	companyAkteGroup := r.Group("/api/CompanyAkte", middleware.AuthorizeJWT(jwtService))
	{
		companyAkteGroup.GET("/count/:companyId", companyAkteController.CountCompanyAkteAll)
		companyAkteGroup.GET("/all/:companyId", companyAkteController.FindCompanyAktes)
		companyAkteGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", companyAkteController.FindCompanyAktesOffset)
		companyAkteGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", companyAkteController.SearchCompanyAkte)
		companyAkteGroup.GET("/countSearch/:search/:companyId", companyAkteController.CountSearchCompanyAkte)
		companyAkteGroup.GET("/:id", companyAkteController.FindCompanyAkteById)
		companyAkteGroup.GET("/byYear/:companyId/:year", companyAkteController.FindCompanyAkteByYear)
		companyAkteGroup.GET("/exc/byYear/:companyId/:year/:companyAkteId", companyAkteController.FindExcCompanyAkteByYear)
		companyAkteGroup.GET("/exc/:id", companyAkteController.FindExcCompanyAkte)
		companyAkteGroup.POST("/", companyAkteController.InsertCompanyAkte)
		companyAkteGroup.PUT("/:id", companyAkteController.UpdateCompanyAkte)
		companyAkteGroup.DELETE("/:id", companyAkteController.DeleteCompanyAkte)
	}

	companyShareholderHistoryGroup := r.Group("/api/companyShareholderHistory", middleware.AuthorizeJWT(jwtService))
	{
		companyShareholderHistoryGroup.GET("/count/:companyId", companyShareholderHistoryController.CountCompanyShareholderHistoryAll)
		companyShareholderHistoryGroup.GET("/all/:companyId", companyShareholderHistoryController.FindCompanyShareholderHistorys)
		companyShareholderHistoryGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", companyShareholderHistoryController.FindCompanyShareholderHistorysOffset)
		companyShareholderHistoryGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", companyShareholderHistoryController.SearchCompanyShareholderHistory)
		companyShareholderHistoryGroup.GET("/countSearch/:search/:companyId", companyShareholderHistoryController.CountSearchCompanyShareholderHistory)
		companyShareholderHistoryGroup.GET("/:id", companyShareholderHistoryController.FindCompanyShareholderHistoryById)
		companyShareholderHistoryGroup.GET("/exc/:id", companyShareholderHistoryController.FindExcCompanyShareholderHistory)
		companyShareholderHistoryGroup.GET("/byCompany/:id", companyShareholderHistoryController.FindCompanyShareholderHistoryByCompanyId)
		companyShareholderHistoryGroup.POST("/", companyShareholderHistoryController.InsertCompanyShareholderHistory)
		companyShareholderHistoryGroup.PUT("/:id", companyShareholderHistoryController.UpdateCompanyShareholderHistory)
		companyShareholderHistoryGroup.DELETE("/:id", companyShareholderHistoryController.DeleteCompanyShareholderHistory)
	}

	companyShareholderHistoryDetailGroup := r.Group("/api/companyShareholderHistoryDetail", middleware.AuthorizeJWT(jwtService))
	{
		companyShareholderHistoryDetailGroup.GET("/count/:companyShareholderHistoryDetailHistoryId", companyShareholderHistoryDetailController.CountCompanyShareholderHistoryDetailAll)
		companyShareholderHistoryDetailGroup.GET("/all/:companyShareholderHistoryDetailHistoryId", companyShareholderHistoryDetailController.FindCompanyShareholderHistoryDetails)
		companyShareholderHistoryDetailGroup.GET("/list/:limit/:offset/:order/:dir/:companyShareholderHistoryDetailHistoryId", companyShareholderHistoryDetailController.FindCompanyShareholderHistoryDetailsOffset)
		companyShareholderHistoryDetailGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyShareholderHistoryDetailHistoryId", companyShareholderHistoryDetailController.SearchCompanyShareholderHistoryDetail)
		companyShareholderHistoryDetailGroup.GET("/countSearch/:search/:companyShareholderHistoryDetailHistoryId", companyShareholderHistoryDetailController.CountSearchCompanyShareholderHistoryDetail)
		companyShareholderHistoryDetailGroup.GET("/byCompany/:id", companyShareholderHistoryDetailController.FindCompanyShareholderHistoryDetailByCompanyId)
		companyShareholderHistoryDetailGroup.GET("/:id", companyShareholderHistoryDetailController.FindCompanyShareholderHistoryDetailById)
		companyShareholderHistoryDetailGroup.GET("/exc/:id", companyShareholderHistoryDetailController.FindExcCompanyShareholderHistoryDetail)
		companyShareholderHistoryDetailGroup.POST("/", companyShareholderHistoryDetailController.InsertCompanyShareholderHistoryDetail)
		companyShareholderHistoryDetailGroup.PUT("/:id", companyShareholderHistoryDetailController.UpdateCompanyShareholderHistoryDetail)
		companyShareholderHistoryDetailGroup.DELETE("/:id", companyShareholderHistoryDetailController.DeleteCompanyShareholderHistoryDetail)
	}

	companyManagementHistoryGroup := r.Group("/api/companyManagementHistory", middleware.AuthorizeJWT(jwtService))
	{
		companyManagementHistoryGroup.GET("/count/:companyId", companyManagementHistoryController.CountCompanyManagementHistoryAll)
		companyManagementHistoryGroup.GET("/all/:companyId", companyManagementHistoryController.FindCompanyManagementHistorys)
		companyManagementHistoryGroup.GET("/list/:limit/:offset/:order/:dir/:companyId", companyManagementHistoryController.FindCompanyManagementHistorysOffset)
		companyManagementHistoryGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyId", companyManagementHistoryController.SearchCompanyManagementHistory)
		companyManagementHistoryGroup.GET("/countSearch/:search/:companyId", companyManagementHistoryController.CountSearchCompanyManagementHistory)
		companyManagementHistoryGroup.GET("/:id", companyManagementHistoryController.FindCompanyManagementHistoryById)
		companyManagementHistoryGroup.GET("/exc/:id", companyManagementHistoryController.FindExcCompanyManagementHistory)
		companyManagementHistoryGroup.GET("/byCompany/:id", companyManagementHistoryController.FindCompanyManagementHistoryByCompanyId)
		companyManagementHistoryGroup.POST("/", companyManagementHistoryController.InsertCompanyManagementHistory)
		companyManagementHistoryGroup.PUT("/:id", companyManagementHistoryController.UpdateCompanyManagementHistory)
		companyManagementHistoryGroup.DELETE("/:id", companyManagementHistoryController.DeleteCompanyManagementHistory)
	}

	companyManagementHistoryDetailGroup := r.Group("/api/companyManagementHistoryDetail", middleware.AuthorizeJWT(jwtService))
	{
		companyManagementHistoryDetailGroup.GET("/count/:companyManagementHistoryDetailHistoryId", companyManagementHistoryDetailController.CountCompanyManagementHistoryDetailAll)
		companyManagementHistoryDetailGroup.GET("/all/:companyManagementHistoryDetailHistoryId", companyManagementHistoryDetailController.FindCompanyManagementHistoryDetails)
		companyManagementHistoryDetailGroup.GET("/list/:limit/:offset/:order/:dir/:companyManagementHistoryDetailHistoryId", companyManagementHistoryDetailController.FindCompanyManagementHistoryDetailsOffset)
		companyManagementHistoryDetailGroup.GET("/search/:limit/:offset/:order/:dir/:search/:companyManagementHistoryDetailHistoryId", companyManagementHistoryDetailController.SearchCompanyManagementHistoryDetail)
		companyManagementHistoryDetailGroup.GET("/countSearch/:search/:companyManagementHistoryDetailHistoryId", companyManagementHistoryDetailController.CountSearchCompanyManagementHistoryDetail)
		companyManagementHistoryDetailGroup.GET("/byCompany/:id", companyManagementHistoryDetailController.FindCompanyManagementHistoryDetailByCompanyId)
		companyManagementHistoryDetailGroup.GET("/:id", companyManagementHistoryDetailController.FindCompanyManagementHistoryDetailById)
		companyManagementHistoryDetailGroup.GET("/exc/:id", companyManagementHistoryDetailController.FindExcCompanyManagementHistoryDetail)
		companyManagementHistoryDetailGroup.POST("/", companyManagementHistoryDetailController.InsertCompanyManagementHistoryDetail)
		companyManagementHistoryDetailGroup.PUT("/:id", companyManagementHistoryDetailController.UpdateCompanyManagementHistoryDetail)
		companyManagementHistoryDetailGroup.DELETE("/:id", companyManagementHistoryDetailController.DeleteCompanyManagementHistoryDetail)
	}

	leavetypesGroup := r.Group("/api/leavetypes", middleware.AuthorizeJWT(jwtService))
	{
		leavetypesGroup.GET("/", leavetypesController.CountLeaveTypesAll)
		leavetypesGroup.GET("/all", leavetypesController.FindLeaveTypess)
		leavetypesGroup.GET("/list/:limit/:offset/:order/:dir", leavetypesController.FindLeaveTypessOffset)
		leavetypesGroup.GET("/search/:limit/:offset/:order/:dir/:search", leavetypesController.SearchLeaveTypes)
		leavetypesGroup.GET("/countSearch/:search", leavetypesController.CountSearchLeaveTypes)
		leavetypesGroup.GET("/:id", leavetypesController.FindLeaveTypesById)
		leavetypesGroup.GET("/CountLeaveTypesName/:search", leavetypesController.CountLeaveTypesName)
		leavetypesGroup.GET("/exc/:id", leavetypesController.FindExcLeaveTypes)
		leavetypesGroup.POST("/", leavetypesController.InsertLeaveTypes)
		leavetypesGroup.PUT("/:id", leavetypesController.UpdateLeaveTypes)
		leavetypesGroup.DELETE("/:id", leavetypesController.DeleteLeaveTypes)
	}

	nonworkingtypeGroup := r.Group("/api/nonworkingtype", middleware.AuthorizeJWT(jwtService))
	{
		nonworkingtypeGroup.GET("/", nonworkingtypeController.CountNonWorkingTypeAll)
		nonworkingtypeGroup.GET("/all", nonworkingtypeController.FindNonWorkingTypes)
		nonworkingtypeGroup.GET("/list/:limit/:offset/:order/:dir", nonworkingtypeController.FindNonWorkingTypesOffset)
		nonworkingtypeGroup.GET("/search/:limit/:offset/:order/:dir/:search", nonworkingtypeController.SearchNonWorkingType)
		nonworkingtypeGroup.GET("/countSearch/:search", nonworkingtypeController.CountSearchNonWorkingType)
		nonworkingtypeGroup.GET("/:id", nonworkingtypeController.FindNonWorkingTypeById)
		nonworkingtypeGroup.GET("/CountNonWorkingTypeName/:search", nonworkingtypeController.CountNonWorkingTypeName)
		nonworkingtypeGroup.GET("/exc/:id", nonworkingtypeController.FindExcNonWorkingType)
		nonworkingtypeGroup.POST("/", nonworkingtypeController.InsertNonWorkingType)
		nonworkingtypeGroup.PUT("/:id", nonworkingtypeController.UpdateNonWorkingType)
		nonworkingtypeGroup.DELETE("/:id", nonworkingtypeController.DeleteNonWorkingType)
	}

	nonworkingdayGroup := r.Group("/api/nonworkingday", middleware.AuthorizeJWT(jwtService))
	{
		nonworkingdayGroup.GET("/", nonworkingdayController.CountNonWorkingDayAll)
		nonworkingdayGroup.GET("/all", nonworkingdayController.FindNonWorkingDays)
		nonworkingdayGroup.GET("/allCuti", nonworkingdayController.FindNonWorkingDaysCuti)
		nonworkingdayGroup.GET("/allCutiDate", nonworkingdayController.FindNonWorkingDaysAllDate)
		nonworkingdayGroup.GET("/list/:limit/:offset/:order/:dir", nonworkingdayController.FindNonWorkingDaysOffset)
		nonworkingdayGroup.GET("/search/:limit/:offset/:order/:dir/:search", nonworkingdayController.SearchNonWorkingDay)
		nonworkingdayGroup.GET("/countSearch/:search", nonworkingdayController.CountSearchNonWorkingDay)
		nonworkingdayGroup.GET("/:id", nonworkingdayController.FindNonWorkingDayById)
		nonworkingdayGroup.GET("/exc/:nwtId/:id", nonworkingdayController.FindExcNonWorkingDay)
		nonworkingdayGroup.GET("/byNWT/:nwtId", nonworkingdayController.FindNonWorkingDayByNWTId)
		nonworkingdayGroup.GET("/byDate/:date", nonworkingdayController.FindNonWorkingDaybyDate)
		nonworkingdayGroup.GET("/CountNonWorkingDayName/:search", nonworkingdayController.CountNonWorkingDayName)
		nonworkingdayGroup.POST("/", nonworkingdayController.InsertNonWorkingDay)
		nonworkingdayGroup.PUT("/:id", nonworkingdayController.UpdateNonWorkingDay)
		nonworkingdayGroup.DELETE("/:id", nonworkingdayController.DeleteNonWorkingDay)
	}

	employeeleavecreditGroup := r.Group("/api/employeeleavecredit", middleware.AuthorizeJWT(jwtService))
	{
		employeeleavecreditGroup.GET("/countAll/:year", employeeleavecreditController.CountEmployeeLeaveCreditAll)
		employeeleavecreditGroup.GET("/all/:year/:empId", employeeleavecreditController.FindEmployeeLeaveCredits)
		employeeleavecreditGroup.GET("/list/:limit/:offset/:order/:dir/:year", employeeleavecreditController.FindEmployeeLeaveCreditsOffset)
		employeeleavecreditGroup.GET("/search/:limit/:offset/:order/:dir/:year/:search", employeeleavecreditController.FindSearchEmployeeLeaveCreditsOffset)
		employeeleavecreditGroup.GET("/countSearch/:year/:search", employeeleavecreditController.CountSearchEmployeeLeaveCreditAll)
		employeeleavecreditGroup.GET("/countByEmp/:year/:empId", employeeleavecreditController.CountEmployeeLeaveCreditEmpID)
		employeeleavecreditGroup.GET("/listEmpId/:limit/:offset/:order/:dir/:year/:empId", employeeleavecreditController.FindEmployeeLeaveCreditsOffsetByYear)
		employeeleavecreditGroup.GET("/searchByEmp/:limit/:offset/:order/:dir/:year/:empId/:search", employeeleavecreditController.FindSearchEmployeeLeaveCreditsOffsetByEmp)
		employeeleavecreditGroup.GET("/countSearchByEmp/:year/:empId/:search", employeeleavecreditController.CountSearchEmployeeLeaveCreditByEmp)
		employeeleavecreditGroup.GET("/searchByDept/:limit/:offset/:order/:dir/:year/:deptId/:positionId/:search/:groupId/:employeeid/:sectionid", employeeleavecreditController.FindSearchEmployeeLeaveCreditsOffsetByDept)
		employeeleavecreditGroup.GET("/countSearchByDept/:year/:deptId/:positionId/:search/:groupId", employeeleavecreditController.CountSearchEmployeeLeaveCreditByDepId)
		employeeleavecreditGroup.GET("/allByDept/:limit/:offset/:order/:dir/:year/:deptId/:positionId/:groupId/:employeeid/:sectionid", employeeleavecreditController.FindEmployeeLeaveCreditsOffsetByDept)
		employeeleavecreditGroup.GET("/countAllByDept/:year/:deptId/:positionId/:groupId", employeeleavecreditController.CountEmployeeLeaveCreditByDepId)
		employeeleavecreditGroup.GET("/allByDiv/:limit/:offset/:order/:dir/:year/:divId/:positionId/:groupId", employeeleavecreditController.FindEmployeeLeaveCreditsOffsetByDivAll)
		employeeleavecreditGroup.GET("/countAllByDiv/:year/:divId/:positionId/:groupId", employeeleavecreditController.CountEmployeeLeaveCreditByDivAll)
		employeeleavecreditGroup.GET("/searchByDiv/:limit/:offset/:order/:dir/:year/:divId/:positionId/:search/:groupId", employeeleavecreditController.FindSearchEmployeeLeaveCreditsOffsetByDivIdAll)
		employeeleavecreditGroup.GET("/countSearchByDiv/:year/:divId/:positionId/:search/:groupId", employeeleavecreditController.CountSearchEmployeeLeaveCreditByDivIdAll)
		employeeleavecreditGroup.GET("/allExc/:year/:empId", employeeleavecreditController.FindEmployeeLeaveCreditsExcEmp)
		employeeleavecreditGroup.GET("/allData/:year", employeeleavecreditController.FindEmployeeLeaveCreditsAll)
		employeeleavecreditGroup.GET("/allByDepMan/:limit/:offset/:order/:dir/:year/:depId/:positionId/:groupId", employeeleavecreditController.FindEmployeeLeaveCreditsOffsetByDepAll)
		employeeleavecreditGroup.GET("/countAllByDepMan/:year/:depId/:positionId/:groupId", employeeleavecreditController.CountEmployeeLeaveCreditByDepAll)
		employeeleavecreditGroup.GET("/searchByDepMan/:limit/:offset/:order/:dir/:year/:depId/:positionId/:search/:groupId", employeeleavecreditController.FindSearchEmployeeLeaveCreditsOffsetByDepIdAll)
		employeeleavecreditGroup.GET("/countSearchByDepMan/:year/:depId/:positionId/:search/:groupId", employeeleavecreditController.CountSearchEmployeeLeaveCreditByDepIdAll)
		// employeeleavecreditGroup.GET("/search/:limit/:offset/:order/:dir/:search", employeeleavecreditController.SearchEmployeeLeaveCredit)
		// employeeleavecreditGroup.GET("/countSearch/:search", employeeleavecreditController.CountSearchEmployeeLeaveCredit)
		employeeleavecreditGroup.GET("/:id", employeeleavecreditController.FindEmployeeLeaveCreditById)
		// employeeleavecreditGroup.GET("/CountEmployeeLeaveCreditName/:search", employeeleavecreditController.CountEmployeeLeaveCreditName)
		employeeleavecreditGroup.GET("/byEmpId/:empid", employeeleavecreditController.FindEmployeeLeaveCreditByEmpId)
		employeeleavecreditGroup.GET("/AllbyEmpId/:empid", employeeleavecreditController.FindAllEmployeeLeaveCreditByEmpId)
		employeeleavecreditGroup.GET("/exc/:id", employeeleavecreditController.FindExcEmployeeLeaveCredit)
		employeeleavecreditGroup.POST("/", employeeleavecreditController.InsertEmployeeLeaveCredit)
		employeeleavecreditGroup.PUT("/:id", employeeleavecreditController.UpdateEmployeeLeaveCredit)
		employeeleavecreditGroup.DELETE("/:id", employeeleavecreditController.DeleteEmployeeLeaveCredit)
	}

	employeeleaverequestGroup := r.Group("/api/employeeleaverequest", middleware.AuthorizeJWT(jwtService))
	{
		employeeleaverequestGroup.GET("/count/:empId", employeeleaverequestController.CountEmployeeLeaveRequestAll)
		employeeleaverequestGroup.GET("/countAll/:year", employeeleaverequestController.CountEmployeeLeaveRequestApprovalAllDt)
		employeeleaverequestGroup.GET("/all", employeeleaverequestController.FindEmployeeLeaveRequests)
		employeeleaverequestGroup.GET("/list/:limit/:offset/:order/:dir/:empId", employeeleaverequestController.FindEmployeeLeaveRequestsOffset)
		employeeleaverequestGroup.GET("/search/:limit/:offset/:order/:dir/:search/:empId", employeeleaverequestController.SearchEmployeeLeaveRequest)
		employeeleaverequestGroup.GET("/countSearch/:search/:empId", employeeleaverequestController.CountSearchEmployeeLeaveRequest)
		employeeleaverequestGroup.GET("/:id", employeeleaverequestController.FindEmployeeLeaveRequestById)
		employeeleaverequestGroup.GET("/countPIC/:empId", employeeleaverequestController.CountEmployeeLeaveRequestAllPIC)
		employeeleaverequestGroup.GET("/listPIC/:limit/:offset/:order/:dir/:empId", employeeleaverequestController.FindEmployeeLeaveRequestsPICOffset)
		employeeleaverequestGroup.GET("/searchPIC/:limit/:offset/:order/:dir/:search/:empId", employeeleaverequestController.CountSearchEmployeeLeaveRequestPIC)
		employeeleaverequestGroup.GET("/countSearchPIC/:search/:empId", employeeleaverequestController.SearchEmployeeLeaveRequestPIC)
		employeeleaverequestGroup.GET("/find/:id", employeeleaverequestController.FindEmployeeLeaveRequestPICById)
		employeeleaverequestGroup.GET("/countDaftarCuti", employeeleaverequestController.CountEmployeeLeaveRequestDaftarCuti)
		employeeleaverequestGroup.GET("/listDaftarCuti/:limit/:offset/:order/:dir", employeeleaverequestController.FindEmployeeLeaveRequestsDaftarCutiOffset)
		employeeleaverequestGroup.GET("/countSearchDaftarCuti/:search", employeeleaverequestController.CountSearchEmployeeLeaveRequestDaftarCuti)
		employeeleaverequestGroup.GET("/searchDaftarCuti/:limit/:offset/:order/:dir/:search", employeeleaverequestController.SearchEmployeeLeaveRequestDaftarCuti)
		employeeleaverequestGroup.GET("/allByEmpId/:empId/:year", employeeleaverequestController.FindEmployeeLeaveRequestByEmpId)
		employeeleaverequestGroup.GET("/allByEmpIdDate/:empId/:year", employeeleaverequestController.FindEmployeeLeaveRequestByEmpIdDate)
		employeeleaverequestGroup.GET("/allByEmpIdExcDate/:elrId/:empId/:year", employeeleaverequestController.FindEmployeeLeaveRequestByEmpIdExcDate)
		employeeleaverequestGroup.GET("/draftorAPA/:empId", employeeleaverequestController.FindEmployeeLeaveRequestDraftOrAFA)
		employeeleaverequestGroup.GET("/byDate/:date", employeeleaverequestController.FindEmployeeLeaveRequestPeriodDate)
		employeeleaverequestGroup.GET("/countPICPersonalia/", employeeleaverequestController.CountEmployeeLeaveRequestPersonaliaAllPIC)
		employeeleaverequestGroup.GET("/listPICPersonalia/:limit/:offset/:order/:dir", employeeleaverequestController.FindEmployeeLeaveRequestsPersonaliaPICOffset)
		employeeleaverequestGroup.GET("/searchPICPersonalia/:limit/:offset/:order/:dir/:search", employeeleaverequestController.CountSearchEmployeeLeaveRequestPersonaliaPIC)
		employeeleaverequestGroup.GET("/countSearchPICPersonalia/:search", employeeleaverequestController.SearchEmployeeLeaveRequestPersonaliaPIC)
		employeeleaverequestGroup.GET("/allDataByEmpId/:empId/:year/:date", employeeleaverequestController.FindAllEmployeeLeaveRequestByEmpId)
		employeeleaverequestGroup.GET("/FromDate/:date", employeeleaverequestController.FindEmployeeLeaveRequestFromDate)
		employeeleaverequestGroup.GET("/ToDate/:date/:date2", employeeleaverequestController.FindEmployeeLeaveRequestToDate)
		employeeleaverequestGroup.GET("/Date/:date/:date2", employeeleaverequestController.FindEmployeeLeaveRequestDate)
		employeeleaverequestGroup.GET("/allDataByEmpIdDate/:empId/:year/:date", employeeleaverequestController.FindAllEmployeeLeaveRequestByEmpIdDate)
		// employeeleaverequestGroup.GET("/exc/:nwtId/:id", employeeleaverequestController.FindExcEmployeeLeaveRequest)
		// employeeleaverequestGroup.GET("/byNWT/:nwtId", employeeleaverequestController.FindEmployeeLeaveRequestByNWTId)
		// employeeleaverequestGroup.GET("/CountEmployeeLeaveRequestName/:search", employeeleaverequestController.CountEmployeeLeaveRequestName)
		employeeleaverequestGroup.POST("/", employeeleaverequestController.InsertEmployeeLeaveRequest)
		employeeleaverequestGroup.PUT("/:id", employeeleaverequestController.UpdateEmployeeLeaveRequest)
		employeeleaverequestGroup.DELETE("/:id", employeeleaverequestController.DeleteEmployeeLeaveRequest)
	}

	employeeleaverequestapprovalGroup := r.Group("/api/employeeleaverequestapproval", middleware.AuthorizeJWT(jwtService))
	{
		employeeleaverequestapprovalGroup.GET("/count/:elrId", employeeleaverequestapprovalController.CountEmployeeLeaveRequestApprovalAll)
		employeeleaverequestapprovalGroup.GET("/all", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovals)
		employeeleaverequestapprovalGroup.GET("/list/:limit/:offset/:order/:dir/:elrId", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalsOffset)
		employeeleaverequestapprovalGroup.GET("/search/:limit/:offset/:order/:dir/:search/:elrId", employeeleaverequestapprovalController.SearchEmployeeLeaveRequestApproval)
		employeeleaverequestapprovalGroup.GET("/countSearch/:search/:elrId", employeeleaverequestapprovalController.CountSearchEmployeeLeaveRequestApproval)
		employeeleaverequestapprovalGroup.GET("/:id", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalById)
		// employeeleaverequestapprovalGroup.GET("/exc/:divId/:id", employeeleaverequestapprovalController.FindExcEmployeeLeaveRequestApproval)
		employeeleaverequestapprovalGroup.GET("/byEmployeeRequestApprove/:elrId", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalApproved)
		employeeleaverequestapprovalGroup.GET("/byEmployeeRequestOpenApprove/:elrId", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalOpenApproved)
		employeeleaverequestapprovalGroup.GET("/byEmployeeRequestOverwrite/:elrId", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalOverwrite)
		employeeleaverequestapprovalGroup.GET("/byEmployeeRequest/:elrId", employeeleaverequestapprovalController.FindEmployeeLeaveRequestApprovalByERId)
		// employeeleaverequestapprovalGroup.GET("/CountEmployeeLeaveRequestApprovalName/:search", employeeleaverequestapprovalController.CountEmployeeLeaveRequestApprovalName)
		employeeleaverequestapprovalGroup.POST("/", employeeleaverequestapprovalController.InsertEmployeeLeaveRequestApproval)
		employeeleaverequestapprovalGroup.PUT("/:id", employeeleaverequestapprovalController.UpdateEmployeeLeaveRequestApproval)
		employeeleaverequestapprovalGroup.DELETE("/:id", employeeleaverequestapprovalController.DeleteEmployeeLeaveRequestApproval)
	}

	employeeleaverequesttracingGroup := r.Group("/api/employeeleaverequesttracing", middleware.AuthorizeJWT(jwtService))
	{
		employeeleaverequesttracingGroup.GET("/count/:employeeLeaveRequestId", employeeleaverequesttracingController.CountEmployeeLeaveRequestTracingAll)
		employeeleaverequesttracingGroup.GET("/all/:employeeLeaveRequestId", employeeleaverequesttracingController.FindEmployeeLeaveRequestTracings)
		employeeleaverequesttracingGroup.GET("/:id", employeeleaverequesttracingController.FindEmployeeLeaveRequestTracingById)
		employeeleaverequesttracingGroup.GET("/exc/:id", employeeleaverequesttracingController.FindExcEmployeeLeaveRequestTracing)
		employeeleaverequesttracingGroup.POST("/", employeeleaverequesttracingController.InsertEmployeeLeaveRequestTracing)
		employeeleaverequesttracingGroup.PUT("/:id", employeeleaverequesttracingController.UpdateEmployeeLeaveRequestTracing)
		employeeleaverequesttracingGroup.DELETE("/:id", employeeleaverequesttracingController.DeleteEmployeeLeaveRequestTracing)
	}

	employeeLeaveRequestDumpGroup := r.Group("/api/EmployeeLeaveRequestDump", middleware.AuthorizeJWT(jwtService))
	{
		employeeLeaveRequestDumpGroup.GET("/", employeeLeaveRequestDumpController.CountEmployeeLeaveRequestDumpAll)
		employeeLeaveRequestDumpGroup.GET("/all", employeeLeaveRequestDumpController.FindEmployeeLeaveRequestDumps)
		employeeLeaveRequestDumpGroup.GET("/list/:limit/:offset/:order/:dir", employeeLeaveRequestDumpController.FindEmployeeLeaveRequestDumpsOffset)
		// employeeLeaveRequestDumpGroup.GET("/search/:limit/:offset/:order/:dir/:search", employeeLeaveRequestDumpController.SearchEmployeeLeaveRequestDump)
		// employeeLeaveRequestDumpGroup.GET("/countSearch/:search", employeeLeaveRequestDumpController.CountSearchEmployeeLeaveRequestDump)
		employeeLeaveRequestDumpGroup.GET("/:id", employeeLeaveRequestDumpController.FindEmployeeLeaveRequestDumpById)
		employeeLeaveRequestDumpGroup.GET("/:id/:tracingID", employeeLeaveRequestDumpController.FindEmployeeLeaveRequestDumpByErlIdandEmp)
		employeeLeaveRequestDumpGroup.GET("/exc/:id", employeeLeaveRequestDumpController.FindExcEmployeeLeaveRequestDump)
		employeeLeaveRequestDumpGroup.POST("/", employeeLeaveRequestDumpController.InsertEmployeeLeaveRequestDump)
		employeeLeaveRequestDumpGroup.PUT("/:id", employeeLeaveRequestDumpController.UpdateEmployeeLeaveRequestDump)
		employeeLeaveRequestDumpGroup.DELETE("/:id", employeeLeaveRequestDumpController.DeleteEmployeeLeaveRequestDump)
	}

	tokenGroup := r.Group("/api/token")
	{
		tokenGroup.POST("/renew", authController.RenewToken)
	}

	// Handle error response when a route is not defined
	r.NoRoute(func(c *gin.Context) {
		// In gin this is how you return a JSON response
		c.JSON(404, gin.H{"message": "Not found"})
	})

	r.Run()
}
