package repository

import (
	"deliportal-api/model"
	"strings"

	"gorm.io/gorm"
)

type EmployeeLeaveRequestApprovalRepository interface {
	CountEmployeeLeaveRequestApprovalAll(elrid int) (count int64, err error)
	FindEmployeeLeaveRequestApprovals() (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	FindEmployeeLeaveRequestApprovalsOffset(limit int, offset int, order string, dir string, elrid int) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	SearchEmployeeLeaveRequestApproval(limit int, offset int, order string, dir string, search string, elrid int) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	CountSearchEmployeeLeaveRequestApproval(search string, elrid int) (count int64, err error)
	FindEmployeeLeaveRequestApprovalById(id uint) (employeeLeaveRequestApprovalOutput model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	// FindExcEmployeeLeaveRequestApproval(divId uint, id uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	FindEmployeeLeaveRequestApprovalApproved(elrid uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	FindEmployeeLeaveRequestApprovalOpenApproved(elrid uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	FindEmployeeLeaveRequestApprovalByERId(elrid uint) (employeeLeaveRequestApprovalOutput model.SelectEmployeeLeaveRequestApprovalParameter, err error)
	// CountEmployeeLeaveRequestApprovalName(search string) (count int64, err error)
	InsertEmployeeLeaveRequestApproval(employeeLeaveRequestApproval model.EmployeeLeaveRequestApproval) (employeeLeaveRequestApprovalOutput model.EmployeeLeaveRequestApproval, err error)
	UpdateEmployeeLeaveRequestApproval(employeeLeaveRequestApproval model.EmployeeLeaveRequestApproval, id uint) (employeeLeaveRequestApprovalOutput model.EmployeeLeaveRequestApproval, err error)
}

type EmployeeLeaveRequestApprovalConnection struct {
	connection *gorm.DB
}

func NewEmployeeLeaveRequestApprovalRepository(db *gorm.DB) EmployeeLeaveRequestApprovalRepository {
	return &EmployeeLeaveRequestApprovalConnection{
		connection: db,
	}
}

func (db *EmployeeLeaveRequestApprovalConnection) CountEmployeeLeaveRequestApprovalAll(elrid int) (count int64, err error) {
	res := db.connection.Debug().Table("employee_leave_request_approvals").Where("employee_leave_request_id = ? AND deleted_at = 0", elrid).Count(&count)
	return count, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovals() (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
	)
	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.deleted_at = 0").Order("employee_leave_request_approvals.employee_leave_request_id").Find(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovalsOffset(limit int, offset int, order string, dir string, elrid int) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		orderDirection                string
		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
	)
	orderDirection = order + " " + dir
	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.employee_leave_request_id = ? AND employee_leave_request_approvals.deleted_at = 0", elrid).Order(orderDirection).Limit(limit).Offset(offset).Find(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) SearchEmployeeLeaveRequestApproval(limit int, offset int, order string, dir string, search string, elrid int) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		orderDirection                string
		final                         string
		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
	)
	orderDirection = order + " " + dir
	final = "%" + strings.ToLower(search) + "%"
	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("(lower(employee_leave_request_approvals.sequence_no::varchar(50)) LIKE ? OR lower(employees.firstname) LIKE ? OR lower(employees.lastname) LIKE ? OR lower(positions.position_name) LIKE ? OR lower(to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY')) LIKE ? OR lower(CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END) LIKE ? OR lower(employee_leave_request_approvals.remark) LIKE ?) AND employee_leave_request_approvals.employee_leave_request_id = ? AND employee_leave_request_approvals.deleted_at = 0", final, final, final, final, final, final, final, elrid).Order(orderDirection).Limit(limit).Offset(offset).Find(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) CountSearchEmployeeLeaveRequestApproval(search string, elrid int) (count int64, err error) {
	final := "%" + strings.ToLower(search) + "%"
	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("(lower(employee_leave_request_approvals.sequence_no::varchar(50)) LIKE ? OR lower(employees.firstname) LIKE ? OR lower(employees.lastname) LIKE ? OR lower(positions.position_name) LIKE ? OR lower(to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY')) LIKE ? OR lower(CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END) LIKE ? OR lower(employee_leave_request_approvals.remark) LIKE ?) AND employee_leave_request_approvals.employee_leave_request_id = ? AND employee_leave_request_approvals.deleted_at = 0", final, final, final, final, final, final, final, elrid).Count(&count)
	return count, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovalById(id uint) (employeeLeaveRequestApprovalOutput model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		employeeLeaveRequestApproval model.SelectEmployeeLeaveRequestApprovalParameter
	)

	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.id=? AND employee_leave_request_approvals.deleted_at = 0", id).Take(&employeeLeaveRequestApproval)
	return employeeLeaveRequestApproval, res.Error
}

// func (db *EmployeeLeaveRequestApprovalConnection) FindExcEmployeeLeaveRequestApproval(divId uint, id uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
// 	var (
// 		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
// 	)

// 	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.division_id = ? AND employee_leave_request_approvals.id!=? AND employee_leave_request_approvals.deleted_at = 0", divId, id).Order("employee_leave_request_approvals.employeeLeaveRequestApproval_name").Find(&employeeLeaveRequestApprovals)
// 	return employeeLeaveRequestApprovals, res.Error
// }

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovalApproved(elrid uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
	)

	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.employee_leave_request_id=? AND employee_leave_request_approvals.deleted_at = 0 AND employee_leave_request_approvals.approval_status=3", elrid).Order("employee_leave_request_approvals.sequence_no").Find(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovalOpenApproved(elrid uint) (employeeLeaveRequestApprovalOutput []model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		employeeLeaveRequestApprovals []model.SelectEmployeeLeaveRequestApprovalParameter
	)

	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.employee_leave_request_id=? AND employee_leave_request_approvals.deleted_at = 0 AND (employee_leave_request_approvals.approval_status=2 OR employee_leave_request_approvals.approval_status=3)", elrid).Order("employee_leave_request_approvals.sequence_no").Find(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) FindEmployeeLeaveRequestApprovalByERId(elrid uint) (employeeLeaveRequestApprovalOutput model.SelectEmployeeLeaveRequestApprovalParameter, err error) {
	var (
		employeeLeaveRequestApprovals model.SelectEmployeeLeaveRequestApprovalParameter
	)

	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("employee_leave_request_approvals.employee_leave_request_id=? AND employee_leave_request_approvals.deleted_at = 0 AND employee_leave_request_approvals.approval_status=1", elrid).Order("employee_leave_request_approvals.sequence_no").Take(&employeeLeaveRequestApprovals)
	return employeeLeaveRequestApprovals, res.Error
}

// func (db *EmployeeLeaveRequestApprovalConnection) CountEmployeeLeaveRequestApprovalName(search string) (count int64, err error) {
// 	final := "%" + strings.ToLower(search) + "%"
// 	res := db.connection.Debug().Table("employee_leave_request_approvals").Select("employee_leave_request_approvals.id, employee_leave_request_approvals.employee_leave_request_id, employee_leave_request_approvals.employee_id, employees.firstname, employees.lastname, employee_leave_request_approvals.sequence_no, employee_leave_request_approvals.division_id, divisions.division_name, employee_leave_request_approvals.department_id, departments.department_name, employee_leave_request_approvals.section_id, sections.section_name,employee_leave_request_approvals.position_id, positions.position_name, to_char(to_timestamp(employee_leave_request_approvals.approved_at::numeric), 'DD-Mon-YYYY') as approved_at, employee_leave_request_approvals.approval_status, CASE WHEN employee_leave_request_approvals.approval_status = 1 THEN 'Pending' WHEN employee_leave_request_approvals.approval_status = 2 THEN 'Open' WHEN employee_leave_request_approvals.approval_status = 3 THEN 'Approved' WHEN employee_leave_request_approvals.approval_status = 4 THEN 'Rejected' END AS approval_status_name, employee_leave_request_approvals.remark, employee_leave_request_approvals.created_user_id, employee_leave_request_approvals.updated_user_id, employee_leave_request_approvals.deleted_user_id, employee_leave_request_approvals.created_at, employee_leave_request_approvals.updated_at, employee_leave_request_approvals.deleted_at").Joins("left join employees ON employee_leave_request_approvals.employee_id = employees.id").Joins("left join divisions ON employee_leave_request_approvals.division_id = divisions.id").Joins("left join departments ON employee_leave_request_approvals.department_id = departments.id").Joins("left join sections ON employee_leave_request_approvals.section_id = sections.id").Joins("left join positions ON employee_leave_request_approvals.position_id = positions.id").Where("lower(employeeLeaveRequestApprovals.employeeLeaveRequestApproval_name) LIKE ?", final).Count(&count)
// 	return count, res.Error
// }

func (db *EmployeeLeaveRequestApprovalConnection) InsertEmployeeLeaveRequestApproval(employeeLeaveRequestApproval model.EmployeeLeaveRequestApproval) (employeeLeaveRequestApprovalOutput model.EmployeeLeaveRequestApproval, err error) {
	res := db.connection.Save(&employeeLeaveRequestApproval)
	return employeeLeaveRequestApproval, res.Error
}

func (db *EmployeeLeaveRequestApprovalConnection) UpdateEmployeeLeaveRequestApproval(employeeLeaveRequestApproval model.EmployeeLeaveRequestApproval, id uint) (employeeLeaveRequestApprovalOutput model.EmployeeLeaveRequestApproval, err error) {
	res := db.connection.Where("id=?", id).Updates(&employeeLeaveRequestApproval)
	return employeeLeaveRequestApproval, res.Error
}
